[project]
name = "plangs2"
version = "0.1.0"
description = "Add a short description here"
authors = ["Emmanuel Oga <contact@github.emmanueloga.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
es-dev = "esbuild --bundle src/frontend/shared/index.css  src/frontend/browse/browse.tsx src/frontend/search/search.tsx --outdir=server/static/ --sourcemap --watch"

[dependencies]
go = ">=1.22.3,<1.23"
esbuild = ">=0.19.2,<0.20"
