// AUTHORING NOTE: This file was seeded once from the legacy PLANGS_GRAPH_SPEC
// (52 edges) during the v3 migration and is now hand-maintained. It is the
// canonical edge catalog for the graph — no build-time codegen depends on it.
import type { EdgeDef } from "./types.ts";

/** The 52 canonical edges of the Plangs graph. */
export const EDGES: readonly EdgeDef[] = [
  {
    name: "plangRelParadigms",
    from: "plang",
    to: "paradigm",
    fromRel: "paradigms",
    toRel: "plangs",
    fromLabel: "Paradigms",
    toLabel: "Plangs",
    pref: "src",
  },
  {
    name: "plangRelPlatforms",
    from: "plang",
    to: "platform",
    fromRel: "platforms",
    toRel: "plangs",
    fromLabel: "Platforms",
    toLabel: "Plangs",
    pref: "src",
  },
  { name: "plangRelTools", from: "plang", to: "tool", fromRel: "tools", toRel: "plangs", fromLabel: "Tools", toLabel: "Plangs", pref: "dst" },
  {
    name: "plangRelTypeSystems",
    from: "plang",
    to: "typeSystem",
    fromRel: "typeSystems",
    toRel: "plangs",
    fromLabel: "Type Systems",
    toLabel: "Plangs",
    pref: "src",
  },
  {
    name: "plangRelCompilesTo",
    from: "plang",
    to: "plang",
    fromRel: "compilesTo",
    toRel: "targetOf",
    fromLabel: "Compiles To",
    toLabel: "Target Of",
    pref: "src",
  },
  {
    name: "plangRelDialectOf",
    from: "plang",
    to: "plang",
    fromRel: "dialectOf",
    toRel: "dialects",
    fromLabel: "Dialect of",
    toLabel: "Dialects",
    pref: "src",
  },
  {
    name: "plangRelImplements",
    from: "plang",
    to: "plang",
    fromRel: "implements",
    toRel: "implementedBy",
    fromLabel: "Implements",
    toLabel: "Implemented By",
    pref: "src",
  },
  {
    name: "plangRelInfluencedBy",
    from: "plang",
    to: "plang",
    fromRel: "influencedBy",
    toRel: "influenced",
    fromLabel: "Influenced By",
    toLabel: "Influenced",
    pref: "src",
  },
  {
    name: "plangRelWrittenWith",
    from: "plang",
    to: "plang",
    fromRel: "writtenWith",
    toRel: "usedToWrite",
    fromLabel: "Written With",
    toLabel: "Used to Write",
    pref: "src",
  },
  { name: "appRelWrittenWith", from: "app", to: "plang", fromRel: "writtenWith", toRel: "apps", fromLabel: "Plangs", toLabel: "Apps", pref: "src" },
  {
    name: "bundleRelPlangs",
    from: "bundle",
    to: "plang",
    fromRel: "plangs",
    toRel: "bundles",
    fromLabel: "Plangs",
    toLabel: "Bundles",
    pref: "none",
  },
  {
    name: "libraryRelPlangs",
    from: "library",
    to: "plang",
    fromRel: "plangs",
    toRel: "libraries",
    fromLabel: "Plangs",
    toLabel: "Libraries",
    pref: "src",
  },
  {
    name: "libraryRelWrittenWith",
    from: "library",
    to: "plang",
    fromRel: "writtenWith",
    toRel: "usedInLibrary",
    fromLabel: "Written With",
    toLabel: "Used for Libraries",
    pref: "src",
  },
  {
    name: "licenseRelPlangs",
    from: "license",
    to: "plang",
    fromRel: "plangs",
    toRel: "licenses",
    fromLabel: "Plangs",
    toLabel: "Licenses",
    pref: "dst",
  },
  {
    name: "subsystemRelWrittenWith",
    from: "subsystem",
    to: "plang",
    fromRel: "writtenWith",
    toRel: "subsystems",
    fromLabel: "Plangs",
    toLabel: "Subsystems",
    pref: "src",
  },
  {
    name: "toolRelWrittenWith",
    from: "tool",
    to: "plang",
    fromRel: "writtenWith",
    toRel: "toolsUsing",
    fromLabel: "Implemented With",
    toLabel: "Tool Plang",
    pref: "src",
  },
  { name: "tagRelApps", from: "tag", to: "app", fromRel: "apps", toRel: "tags", fromLabel: "Apps", toLabel: "Tags", pref: "dst" },
  {
    name: "tagRelCommunities",
    from: "tag",
    to: "community",
    fromRel: "communities",
    toRel: "tags",
    fromLabel: "Communities",
    toLabel: "Tags",
    pref: "dst",
  },
  {
    name: "tagRelLearning",
    from: "tag",
    to: "learning",
    fromRel: "learning",
    toRel: "tags",
    fromLabel: "Learning Resources",
    toLabel: "Tags",
    pref: "dst",
  },
  { name: "tagRelLibraries", from: "tag", to: "library", fromRel: "libraries", toRel: "tags", fromLabel: "Libraries", toLabel: "Tags", pref: "dst" },
  { name: "tagRelPlangs", from: "tag", to: "plang", fromRel: "plangs", toRel: "tags", fromLabel: "Plangs", toLabel: "Tags", pref: "dst" },
  {
    name: "tagRelSubsystems",
    from: "tag",
    to: "subsystem",
    fromRel: "subsystems",
    toRel: "tags",
    fromLabel: "Subsystems",
    toLabel: "Tags",
    pref: "dst",
  },
  { name: "tagRelTools", from: "tag", to: "tool", fromRel: "tools", toRel: "tags", fromLabel: "Tools", toLabel: "Tags", pref: "dst" },
  { name: "postRelApps", from: "post", to: "app", fromRel: "apps", toRel: "posts", fromLabel: "Apps", toLabel: "Posts", pref: "none" },
  {
    name: "postRelCommunities",
    from: "post",
    to: "community",
    fromRel: "communities",
    toRel: "posts",
    fromLabel: "Communities",
    toLabel: "Posts",
    pref: "none",
  },
  {
    name: "postRelLearning",
    from: "post",
    to: "learning",
    fromRel: "learning",
    toRel: "posts",
    fromLabel: "Learning Resources",
    toLabel: "Posts",
    pref: "none",
  },
  {
    name: "postRelLibraries",
    from: "post",
    to: "library",
    fromRel: "libraries",
    toRel: "posts",
    fromLabel: "Libraries",
    toLabel: "Posts",
    pref: "none",
  },
  { name: "postRelPlangs", from: "post", to: "plang", fromRel: "plangs", toRel: "posts", fromLabel: "Plangs", toLabel: "Posts", pref: "none" },
  {
    name: "postRelSubsystems",
    from: "post",
    to: "subsystem",
    fromRel: "subsystems",
    toRel: "posts",
    fromLabel: "Subsystems",
    toLabel: "Posts",
    pref: "none",
  },
  { name: "postRelTools", from: "post", to: "tool", fromRel: "tools", toRel: "posts", fromLabel: "Tools", toLabel: "Posts", pref: "none" },
  {
    name: "communityRelApps",
    from: "community",
    to: "app",
    fromRel: "apps",
    toRel: "communities",
    fromLabel: "Apps",
    toLabel: "Communities",
    pref: "src",
  },
  {
    name: "communityRelLibraries",
    from: "community",
    to: "library",
    fromRel: "libraries",
    toRel: "communities",
    fromLabel: "Libraries",
    toLabel: "Communities",
    pref: "src",
  },
  {
    name: "communityRelPlangs",
    from: "community",
    to: "plang",
    fromRel: "plangs",
    toRel: "communities",
    fromLabel: "Plangs",
    toLabel: "Communities",
    pref: "src",
  },
  {
    name: "communityRelSubsystems",
    from: "community",
    to: "subsystem",
    fromRel: "subsystems",
    toRel: "communities",
    fromLabel: "Subsystems",
    toLabel: "Communities",
    pref: "src",
  },
  {
    name: "communityRelTools",
    from: "community",
    to: "tool",
    fromRel: "tools",
    toRel: "communities",
    fromLabel: "Tools",
    toLabel: "Communities",
    pref: "src",
  },
  {
    name: "learningRelApps",
    from: "learning",
    to: "app",
    fromRel: "apps",
    toRel: "learning",
    fromLabel: "Apps",
    toLabel: "Learning Resources",
    pref: "src",
  },
  {
    name: "learningRelCommunities",
    from: "learning",
    to: "community",
    fromRel: "communities",
    toRel: "learning",
    fromLabel: "Communities",
    toLabel: "Learning Resources",
    pref: "src",
  },
  {
    name: "learningRelLibraries",
    from: "learning",
    to: "library",
    fromRel: "libraries",
    toRel: "learning",
    fromLabel: "Libraries",
    toLabel: "Learning Resources",
    pref: "src",
  },
  {
    name: "learningRelPlangs",
    from: "learning",
    to: "plang",
    fromRel: "plangs",
    toRel: "learning",
    fromLabel: "Plangs",
    toLabel: "Learning Resources",
    pref: "src",
  },
  {
    name: "learningRelSubsystems",
    from: "learning",
    to: "subsystem",
    fromRel: "subsystems",
    toRel: "learning",
    fromLabel: "Subsystems",
    toLabel: "Learning Resources",
    pref: "src",
  },
  {
    name: "learningRelTools",
    from: "learning",
    to: "tool",
    fromRel: "tools",
    toRel: "learning",
    fromLabel: "Tools",
    toLabel: "Learning Resources",
    pref: "src",
  },
  { name: "licenseRelApps", from: "license", to: "app", fromRel: "apps", toRel: "licenses", fromLabel: "Apps", toLabel: "Licenses", pref: "dst" },
  {
    name: "licenseRelLibraries",
    from: "license",
    to: "library",
    fromRel: "libraries",
    toRel: "licenses",
    fromLabel: "Libraries",
    toLabel: "Licenses",
    pref: "dst",
  },
  {
    name: "licenseRelSubsystems",
    from: "license",
    to: "subsystem",
    fromRel: "subsystems",
    toRel: "licenses",
    fromLabel: "Subsystems",
    toLabel: "Licenses",
    pref: "dst",
  },
  { name: "licenseRelTools", from: "license", to: "tool", fromRel: "tools", toRel: "licenses", fromLabel: "Tools", toLabel: "Licenses", pref: "dst" },
  { name: "appRelPlatforms", from: "app", to: "platform", fromRel: "platforms", toRel: "apps", fromLabel: "Platforms", toLabel: "Apps", pref: "src" },
  { name: "bundleRelTools", from: "bundle", to: "tool", fromRel: "tools", toRel: "bundles", fromLabel: "Tools", toLabel: "Bundles", pref: "src" },
  {
    name: "libraryRelPlatforms",
    from: "library",
    to: "platform",
    fromRel: "platforms",
    toRel: "libraries",
    fromLabel: "Platforms",
    toLabel: "Libraries",
    pref: "src",
  },
  {
    name: "subsystemRelPlatforms",
    from: "subsystem",
    to: "platform",
    fromRel: "platforms",
    toRel: "subsystems",
    fromLabel: "Platforms",
    toLabel: "Subsystems",
    pref: "src",
  },
  {
    name: "toolRelPlatforms",
    from: "tool",
    to: "platform",
    fromRel: "platforms",
    toRel: "tools",
    fromLabel: "Platforms",
    toLabel: "Tools",
    pref: "src",
  },
  { name: "postRelAuthors", from: "post", to: "author", fromRel: "authors", toRel: "posts", fromLabel: "Authors", toLabel: "Posts", pref: "none" },
  {
    name: "authorRelCommunites",
    from: "author",
    to: "community",
    fromRel: "communites",
    toRel: "members",
    fromLabel: "Communites",
    toLabel: "Members",
    pref: "src",
  },
] as const;
