import type { PlangsGraph } from "../../../entities/plangs_graph";

export function define(g: PlangsGraph) {
  const lb = g.plangBuilder;

  lb.define(
    "pl+algol",
    "ALGOL 60",
    {
      name: "ALGOL 60",
      websites: [
        { kind: "wikipedia", title: "ALGOL", href: "https://en.wikipedia.org/wiki/ALGOL" },
        { kind: "wikipedia", title: "ALGOL 60", href: "https://en.wikipedia.org/wiki/ALGOL_60" },
        { kind: "wikipedia", title: "ALGOL 68", href: "https://en.wikipedia.org/wiki/ALGOL_68" },
        { kind: "wikipedia", title: "PS-algol", href: "https://en.wikipedia.org/wiki/PS-algol" },
        { kind: "wikipedia", title: "S-algol", href: "https://en.wikipedia.org/wiki/S-algol" },
        { kind: "wikipedia", title: "ALGOL 68C", href: "https://en.wikipedia.org/wiki/ALGOL_68C" },
        { kind: "wikipedia", title: "ALGOL 68-R", href: "https://en.wikipedia.org/wiki/ALGOL_68-R" },
        { kind: "wikipedia", title: "ALGOL 68RS", href: "https://en.wikipedia.org/wiki/ALGOL_68RS" },
        { kind: "wikipedia", title: "ALGOL 68S", href: "https://en.wikipedia.org/wiki/ALGOL_68S" },
        { kind: "wikipedia", title: "ALGOL Y", href: "https://en.wikipedia.org/wiki/ALGOL_Y" },
        { kind: "wikipedia", title: "ALGOL W", href: "https://en.wikipedia.org/wiki/ALGOL_W" },
        { kind: "wikipedia", title: "ALGOL 58", href: "https://en.wikipedia.org/wiki/ALGOL_58" },
        { kind: "wikipedia", title: "Algol-like", href: "https://en.wikipedia.org/wiki/Algol-like" },
        { kind: "wikipedia", title: "Dartmouth ALGOL 30", href: "https://en.wikipedia.org/wiki/Dartmouth_ALGOL_30" },
      ],
      releases: [
        { version: "unknown", date: "1983-01-01", kind: "first" },
        { version: "unknown", date: "1968-01-01", kind: "first" },
        { version: "unknown", date: "1973-01-01", kind: "stable" },
        { version: "unknown", date: "1958-01-01", kind: "first" },
        { version: "unknown", date: "1966-01-01", kind: "first" },
        { version: "unknown", date: "1961-01-01", kind: "first" },
        { version: "unknown", date: "1960-01-01", kind: "first" },
        { version: "unknown", date: "1977-01-01", kind: "first" },
      ],
      images: [
        {
          kind: "logo",
          url: "https://upload.wikimedia.org/wikipedia/en/thumb/3/35/Algol68RevisedReportCover.jpg/121px-Algol68RevisedReportCover.jpg",
        },
        {
          kind: "logo",
          url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/1965_ALGOL-20_A_Language_Manual%2C_Fierst_et_al_-_cover.jpg/121px-1965_ALGOL-20_A_Language_Manual%2C_Fierst_et_al_-_cover.jpg",
        },
      ],
    },
    {
      dialects: [
        "pl+coral",
        "pl+euler",
        "pl+atlas-autocode",
        "pl+jovial",
        "pl+algol",
        "pl+rtl-slash2",
        "pl+simula-67",
        "pl+newp",
        "pl+executive-systems-problem-oriented",
        "pl+imp",
        "pl+napier88",
        "pl+edinburgh-imp",
        "pl+pl360",
        "pl+small",
        "pl+mad",
        "pl+sail",
      ],
      implementations: ["pl+algol", "pl+flacc", "pl+odra", "pl+pl360", "pl+assembly", "pl+bliss"],
      influences: ["pl+algol", "pl+fortran", "pl+plankalkul", "pl+superplan", "pl+pl360", "pl+speedcoding"],
      paradigms: ["para+multi", "para+imperative", "para+structured", "para+concurrent"],
      people: [
        "person+ron-morrison",
        "person+paul-cockshott",
        "person+a-van-wijngaarden",
        "person+b-j-mailloux",
        "person+j-e-l-peck",
        "person+c-h-a-koster",
        "person+van-wijngaarden",
        "person+friedrich-l-bauer",
        "person+hermann-bottenbruch",
        "person+heinz-rutishauser",
        "person+klaus-samelson",
        "person+john-backus",
        "person+charles-katz",
        "person+alan-perlis",
        "person+joseph-henry-wegstein",
        "person+niklaus-wirth",
        "person+tony-hoare",
        "person+anthony-w-knapp",
        "person+thomas-e-kurtz",
        "person+charles-h-lindsey",
      ],
      platforms: ["platf+atari"],
      typeSystems: ["tsys+static", "tsys+strong", "tsys+safe", "tsys+structural"],
    },
  );
}
