import type { PlangsGraph } from "../../../entities/plangs_graph";

export function define(g: PlangsGraph) {
  const lb = g.plangBuilder;

  lb.define(
    "pl+basic",
    "BASIC",
    {
      name: "BASIC",
      websites: [
        {
          kind: "wikipedia",
          title: "IBM Cassette BASICIBM Disk BASICIBM Advanced BASIC (BASICA)",
          href: "https://en.wikipedia.org/wiki/IBM_BASICA",
        },
        { kind: "wikipedia", title: "GW-BASIC", href: "https://en.wikipedia.org/wiki/GW-BASIC" },
        { kind: "wikipedia", title: "BASIC", href: "https://en.wikipedia.org/wiki/BASIC" },
        { kind: "wikipedia", title: "Level I BASIC", href: "https://en.wikipedia.org/wiki/Level_I_BASIC" },
        { kind: "wikipedia", title: "Tiny BASIC", href: "https://en.wikipedia.org/wiki/Tiny_BASIC" },
        {
          kind: "wikipedia",
          title: "TRS-80 Level II BASIC",
          href: "https://en.wikipedia.org/wiki/TRS-80_Level_II_BASIC",
        },
        { kind: "wikipedia", title: "B4x", href: "https://en.wikipedia.org/wiki/Basic4ppc" },
        { kind: "homepage", title: "www.b4x.com", href: "http://www.b4x.com" },
        { kind: "wikipedia", title: "Visual Basic", href: "https://en.wikipedia.org/wiki/Visual_Basic" },
        { kind: "wikipedia", title: "Dartmouth BASIC", href: "https://en.wikipedia.org/wiki/Dartmouth_BASIC" },
        { kind: "wikipedia", title: "Atari BASIC", href: "https://en.wikipedia.org/wiki/Atari_BASIC" },
        {
          kind: "wikipedia",
          title: "Data General Business Basic",
          href: "https://en.wikipedia.org/wiki/Data_General_Business_Basic",
        },
        { kind: "wikipedia", title: "BASIC A+", href: "https://en.wikipedia.org/wiki/BASIC_A%2B" },
        { kind: "wikipedia", title: "BASIC XL", href: "https://en.wikipedia.org/wiki/BASIC_XL" },
        { kind: "wikipedia", title: "Turbo-BASIC XL", href: "https://en.wikipedia.org/wiki/Turbo-BASIC_XL" },
        { kind: "wikipedia", title: "SUPER BASIC", href: "https://en.wikipedia.org/wiki/Tymshare_SUPER_BASIC" },
        { kind: "wikipedia", title: "BASIC-PLUS", href: "https://en.wikipedia.org/wiki/BASIC-PLUS" },
        {
          kind: "wikipedia",
          title: "Visual Basic for Applications",
          href: "https://en.wikipedia.org/wiki/Visual_Basic_for_Applications",
        },
        { kind: "wikipedia", title: "QuickBASIC", href: "https://en.wikipedia.org/wiki/QuickBASIC" },
        { kind: "wikipedia", title: "Visual Basic", href: "https://en.wikipedia.org/wiki/Visual_Basic_(classic)" },
        { kind: "wikipedia", title: "Vilnius Basic", href: "https://en.wikipedia.org/wiki/Vilnius_BASIC" },
        { kind: "wikipedia", title: "MSX BASIC", href: "https://en.wikipedia.org/wiki/MSX_BASIC" },
        { kind: "wikipedia", title: "Business Basic", href: "https://en.wikipedia.org/wiki/Business_Basic" },
        { kind: "wikipedia", title: "Microsoft BASIC", href: "https://en.wikipedia.org/wiki/Microsoft_BASIC" },
        {
          kind: "wikipedia",
          title: "Microsoft Small Basic",
          href: "https://en.wikipedia.org/wiki/Microsoft_Small_Basic",
        },
        { kind: "homepage", title: "www.microsoft.com", href: "https://www.microsoft.com/" },
        { kind: "homepage", title: "www.microsoft.com", href: "http://www.microsoft.com" },
        { kind: "wikipedia", title: "NSB/AppStudio", href: "https://en.wikipedia.org/wiki/NS_Basic" },
        { kind: "homepage", title: "www.appstudio.dev", href: "https://www.appstudio.dev" },
        {
          kind: "homepage",
          title:
            "learn.microsoft.com/en-us/previous-versions/visualstudio/visual-basic-6/visual-basic-6.0-documentation",
          href: "https://learn.microsoft.com/en-us/previous-versions/visualstudio/visual-basic-6/visual-basic-6.0-documentation",
        },
        { kind: "wikipedia", title: "QBasic", href: "https://en.wikipedia.org/wiki/QBasic" },
        { kind: "wikipedia", title: "Visual Basic .NET", href: "https://en.wikipedia.org/wiki/Visual_Basic_.NET" },
        { kind: "wikipedia", title: "Basic4android", href: "https://en.wikipedia.org/wiki/Basic4android" },
        { kind: "wikipedia", title: "Liberty BASIC", href: "https://en.wikipedia.org/wiki/Liberty_BASIC" },
        { kind: "homepage", title: "libertybasic.com", href: "http://libertybasic.com" },
        { kind: "wikipedia", title: "IBM Cassette BASIC", href: "https://en.wikipedia.org/wiki/IBM_Cassette_BASIC" },
        { kind: "wikipedia", title: "IBM Disk BASIC", href: "https://en.wikipedia.org/wiki/IBM_Disk_BASIC" },
        { kind: "wikipedia", title: "PowerBASIC", href: "https://en.wikipedia.org/wiki/PowerBASIC" },
        { kind: "homepage", title: "www.powerbasic.com", href: "https://www.powerbasic.com/" },
        { kind: "wikipedia", title: "Turbo Basic", href: "https://en.wikipedia.org/wiki/Turbo_Basic" },
        { kind: "wikipedia", title: "SmallBASIC", href: "https://en.wikipedia.org/wiki/SmallBasic" },
        { kind: "repository", title: "smallbasic.github.io", href: "https://smallbasic.github.io" },
        { kind: "wikipedia", title: "FreeBASIC", href: "https://en.wikipedia.org/wiki/FreeBASIC" },
        { kind: "homepage", title: "www.freebasic.net", href: "http://www.freebasic.net" },
        { kind: "wikipedia", title: "Applesoft BASIC", href: "https://en.wikipedia.org/wiki/Applesoft_BASIC" },
        { kind: "wikipedia", title: "Sinclair BASIC", href: "https://en.wikipedia.org/wiki/Sinclair_BASIC" },
        { kind: "wikipedia", title: "BBC BASIC", href: "https://en.wikipedia.org/wiki/BBC_BASIC" },
        {
          kind: "homepage",
          title: "smallbasic-publicwebsite.azurewebsites.net",
          href: "https://smallbasic-publicwebsite.azurewebsites.net/",
        },
        { kind: "wikipedia", title: "Commodore BASIC", href: "https://en.wikipedia.org/wiki/Commodore_BASIC" },
        { kind: "wikipedia", title: "TI-BASIC", href: "https://en.wikipedia.org/wiki/TI-BASIC" },
        { kind: "wikipedia", title: "Casio BASIC", href: "https://en.wikipedia.org/wiki/Casio_BASIC" },
      ],
      images: [
        {
          kind: "logo",
          url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/IBM_Cassette_BASIC.png/300px-IBM_Cassette_BASIC.png",
        },
        {
          kind: "logo",
          url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/AtariBasicExample.png/300px-AtariBasicExample.png",
        },
        {
          kind: "logo",
          url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Turbo-BASIC_XL-1.5.png/220px-Turbo-BASIC_XL-1.5.png",
        },
        {
          kind: "logo",
          url: "https://upload.wikimedia.org/wikipedia/commons/7/78/Microsoft_Visual_Basic_for_Applications_logo.svg",
        },
        {
          kind: "logo",
          url: "https://upload.wikimedia.org/wikipedia/en/thumb/0/01/QuickBasic_Opening_Screen.png/220px-QuickBasic_Opening_Screen.png",
        },
        {
          kind: "logo",
          url: "https://upload.wikimedia.org/wikipedia/en/thumb/e/e4/Visual_Basic_6.0_logo.png/210px-Visual_Basic_6.0_logo.png",
        },
        {
          kind: "logo",
          url: "https://upload.wikimedia.org/wikipedia/en/thumb/6/6b/GW-BASIC_3.23.png/300px-GW-BASIC_3.23.png",
        },
        {
          kind: "logo",
          url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/PowerBasic-screen-shot.png/300px-PowerBasic-screen-shot.png",
        },
        { kind: "logo", url: "https://upload.wikimedia.org/wikipedia/en/2/22/Smallbasic-screenshot-3spiros.png" },
        { kind: "logo", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Fblogo.gif/121px-Fblogo.gif" },
        {
          kind: "logo",
          url: "https://upload.wikimedia.org/wikipedia/en/thumb/6/6b/Small_Basic.png/300px-Small_Basic.png",
        },
        {
          kind: "logo",
          url: "https://upload.wikimedia.org/wikipedia/en/thumb/0/01/QBasic_Opening_Screen.png/220px-QBasic_Opening_Screen.png",
        },
        {
          kind: "logo",
          url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/AtariBASIC.png/300px-AtariBASIC.png",
        },
      ],
      releases: [
        { version: "unknown", date: "1981-01-01", kind: "first" },
        { version: "unknown", date: "1977-01-01", kind: "first" },
        { version: "unknown", date: "2005-01-01", kind: "first" },
        { version: "unknown", date: "1964-01-01", kind: "first" },
        { version: "unknown", date: "1979-01-01", kind: "first" },
        { version: "unknown", date: "1983-01-01", kind: "stable" },
        { version: "unknown", date: "1976-01-01", kind: "first" },
        { version: "unknown", date: "1968-01-01", kind: "first" },
        { version: "unknown", date: "1985-01-01", kind: "first" },
        { version: "unknown", date: "1993-01-01", kind: "first" },
        { version: "7.1", kind: "stable" },
        { version: "unknown", date: "1975-01-01", kind: "first" },
        { version: "unknown", date: "2018-01-01", kind: "stable" },
        { version: "unknown", date: "1986-01-01", kind: "first" },
        { version: "unknown", date: "1970-01-01", kind: "first" },
        { version: "unknown", date: "1990-01-01", kind: "stable" },
        { version: "4.1", kind: "stable" },
        { version: "9.0.4", date: "2024-05-01", kind: "stable" },
        { version: "unknown", date: "1991-01-01", kind: "first" },
        { version: "unknown", date: "1992-01-01", kind: "first" },
        { version: "4.5.1", date: "2017-05-31", kind: "stable" },
        { version: "3.23", date: "1988-01-01", kind: "stable" },
        { version: "unknown", date: "1989-01-01", kind: "first" },
        { version: "10.0", date: "2011-05-04", kind: "stable" },
        { version: "12.27", date: "2024-04-26", kind: "stable" },
        { version: "unknown", date: "2004-01-01", kind: "first" },
        { version: "1.10.1", date: "2023-12-25", kind: "stable" },
        { version: "unknown", date: "1978-01-01", kind: "stable" },
        { version: "unknown", date: "2008-10-23", kind: "first" },
        { version: "1.2", date: "2015-10-01", kind: "stable" },
        { version: "7.0", date: "1985-01-01", kind: "stable" },
        { version: "10.0", date: "1991-01-01", kind: "preview" },
        { version: "unknown", date: "1964-05-01", kind: "first" },
      ],
      extensions: [".bas", ".fr3", ".bas", ".sb"],
      references: {
        license: [
          {
            href: "https://devblogs.microsoft.com/commandline/microsoft-open-sources-gw-basic/",
            title: "Microsoft Open-Sources GW-BASIC",
          },
          { href: "https://github.com/sb/smallbasic-editor/blob/master/LICENSE", title: "SmallBasic" },
        ],
        stable_release: [
          {
            href: "https://www.powerbasic.com/support/pbforums/showthread.php?t=047454",
            title: "Release of PowerBASIC 10.0 Compiler for Windows",
          },
          { href: "https://smallbasic.github.io", title: "Browse Files for SmallBASIC" },
        ],
        designed_by: [
          { href: "https://www.freebasic.net/about.html", title: "freeBASIC about page" },
          {
            href: "https://books.google.com/books?id=YXVVngEACAAJ",
            title: "Programming Games with Microsoft Small Basic",
          },
          {
            href: "https://techcommunity.microsoft.com/t5/small-basic-blog/featured-article-interviews-with-vijaye-raji-the-creator-of/ba-p/337729",
            title: "Featured Article: Interviews with Vijaye Raji, the creator of Small Basic",
          },
        ],
      },
    },
    {
      dialects: ["pl+basic", "pl+open"],
      implementations: ["pl+assembly", "pl+basic", "pl+mos-6502", "pl+ms-visual-studio", "pl+qb64"],
      influences: [
        "pl+algol",
        "pl+basic",
        "pl+c",
        "pl+cal",
        "pl+darsimco",
        "pl+focal",
        "pl+fortran",
        "pl+joss",
        "pl+li-chen-wang",
        "pl+logo",
        "pl+objectlogo",
        "pl+speedcoding",
      ],
      licenses: [
        "lic+commercial",
        "lic+eula",
        "lic+gpl",
        "lic+gpl3",
        "lic+lgpl",
        "lic+mit",
        "lic+ms",
        "lic+proprietary",
      ],
      paradigms: [
        "para+algorithmic",
        "para+array",
        "para+event",
        "para+imperative",
        "para+multi",
        "para+non",
        "para+objects",
        "para+structured",
      ],
      people: [
        ["person+andre-victor", { role: "designer" }],
        ["person+carl-gundel", { role: "designer" }],
        ["person+dennis-allison", { role: "designer" }],
        ["person+john-g-kemeny", { role: "designer" }],
        ["person+kathleen-o-brien", { role: "designer" }],
        ["person+li-chen-wang", { role: "developer" }],
        ["person+paul-laughton", { role: "designer" }],
        ["person+robert--bob--zale", { role: "developer" }],
        ["person+steve-leininger", { role: "designer" }],
        ["person+steve-vickers", { role: "designer" }],
        ["person+thomas-e-kurtz", { role: "designer" }],
      ],
      platforms: [
        "platf+.net",
        "platf+android",
        "platf+arcaos",
        "platf+arduino",
        "platf+atari",
        "platf+bsd",
        "platf+commodore",
        "platf+dos",
        "platf+linux",
        "platf+mac",
        "platf+web",
        "platf+win",
        "platf+x86",
        "platf+zx-spectrum",
        "platf+zx80",
        "platf+zx81",
      ],
      typeSystems: ["tsys+dynamic", "tsys+static", "tsys+strong", "tsys+weak"],
    },
  );

  lb.define(
    "pl+gambas",
    "Gambas",
    {
      name: "Gambas",
      websites: [
        { kind: "wikipedia", title: "Gambas", href: "https://en.wikipedia.org/wiki/Gambas" },
        { kind: "homepage", title: "http://gambas.sourceforge.net", href: "http://gambas.sourceforge.net" },
      ],
      images: [
        {
          kind: "logo",
          url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Gambas_mascot.png/95px-Gambas_mascot.png",
        },
      ],
      releases: [
        { version: "unknown", date: "1999-01-01", kind: "first" },
        { version: "3.19.1", date: "2024-03-17", kind: "stable" },
      ],
      references: {
        stable_release: [
          { href: "https://gitlab.com/gambas/gambas/-/releases", title: "Releases · Gambas / gambas · GitLab" },
        ],
        os: [
          { href: "https://allbasic.info/forum/index.php?topic=118.0", title: "Gambas 3 OS X" },
          { href: "https://discuss.haiku-os.org/t/gambas-on-haiku/10500", title: "Gambas on Haiku?" },
        ],
        influenced_by: [
          { href: "http://gambaswiki.org/wiki/doc/intro?nh&l=en", title: "Gambas Documentation Introduction" },
        ],
      },
    },
    {
      influences: ["pl+basic", "pl+java"],
      licenses: ["lic+gpl"],
      people: [["person+benoit-minisini", { role: "designer" }]],
      platforms: ["platf+bsd", "platf+cygwin", "platf+haiku", "platf+linux", "platf+mac", "platf+win"],
    },
  );

  lb.define(
    "pl+xojo",
    "Xojo",
    {
      name: "Xojo",
      websites: [
        { kind: "wikipedia", title: "Xojo", href: "https://en.wikipedia.org/wiki/Xojo" },
        { kind: "homepage", title: "xojo.com", href: "http://xojo.com" },
      ],
      images: [{ kind: "logo", url: "https://upload.wikimedia.org/wikipedia/commons/3/31/Logomark_Xojo_Company.svg" }],
      references: { stable_release: [{ href: "https://www.xojo.com/download/", title: "Xojo: Downloads" }] },
      releases: [{ version: "3.1", date: "2023-10-25", kind: "stable" }],
    },
    { influences: ["pl+basic"], licenses: ["lic+freemium"] },
  );
}
