import type { PlangsGraph } from "../../../entities/plangs_graph";

export function define(g: PlangsGraph) {
  const lb = g.plangBuilder;

  lb.define(
    "pl+c",
    "C",
    {
      name: "C",
      websites: [
        { kind: "wikipedia", title: "C", href: "https://en.wikipedia.org/wiki/C_(programming_language)" },
        {
          kind: "wikipedia",
          title: "C Programming Language",
          href: "https://en.wikipedia.org/wiki/C_Programming_Language",
        },
        { kind: "homepage", title: "www.iso.org/standard/74528.html", href: "https://www.iso.org/standard/74528.html" },
        {
          kind: "homepage",
          title: "www.open-std.org/jtc1/sc22/wg14/",
          href: "http://www.open-std.org/jtc1/sc22/wg14/",
        },
      ],
      images: [
        {
          kind: "logo",
          url: "https://upload.wikimedia.org/wikipedia/commons/3/35/The_C_Programming_Language_logo.svg",
        },
      ],
      releases: [
        { version: "unknown", date: "1972-01-01", kind: "first" },
        { version: "unknown", date: "2018-01-01", kind: "stable" },
        { version: "unknown", date: "2024-02-21", kind: "preview" },
      ],
      references: {
        preview_release: [
          {
            href: "https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3221.htm",
            title: "N3221 - Editor's Report, Post January 2024 Strasbourg France Meeting",
          },
        ],
        influenced: [
          {
            href: "https://web.archive.org/web/20131106064022/http://cs.anu.edu.au/courses/ENGN3213/lectures/lecture6_VERILOG_2010.pdf",
            title: "Verilog HDL (and C)",
          },
        ],
      },
      extensions: [".c", ".h"],
    },
    {
      dialects: [
        "pl+c-star",
        "pl+carbon",
        "pl+cilk",
        "pl+cpp",
        "pl+cyclone",
        "pl+objective-cpp",
        "pl+split-c",
        "pl+unified-parallel-c",
      ],
      implementations: [
        "pl+clang",
        "pl+cppbuilder",
        "pl+gcc",
        "pl+intel-cpp-compiler",
        "pl+ms-visual-cpp",
        "pl+portable-c-compiler",
        "pl+watcom-c-slashcpp",
      ],
      influenced: [
        "pl+alef",
        "pl+ampl",
        "pl+awk",
        "pl+bs",
        "pl+c-",
        "pl+c-sharp",
        "pl+c-shell",
        "pl+cg",
        "pl+chapel",
        "pl+charm",
        "pl+cilk-plus",
        "pl+claire",
        "pl+cpp",
        "pl+crystal",
        "pl+cyclone",
        "pl+cython",
        "pl+d",
        "pl+dart",
        "pl+draco",
        "pl+ec",
        "pl+ecmascript",
        "pl+embeddable-common-lisp",
        "pl+fpgac",
        "pl+freebasic",
        "pl+go",
        "pl+godot",
        "pl+handel-c",
        "pl+java",
        "pl+javascript",
        "pl+jspp",
        "pl+julia",
        "pl+limbo",
        "pl+lpc",
        "pl+newlisp",
        "pl+newsqueak",
        "pl+nim",
        "pl+objective-c",
        "pl+objective-cpp",
        "pl+ocaml",
        "pl+pcastl",
        "pl+perl",
        "pl+php",
        "pl+pike",
        "pl+processing",
        "pl+python",
        "pl+quakec",
        "pl+rapid",
        "pl+ratfiv",
        "pl+ring",
        "pl+rust",
        "pl+s",
        "pl+sac",
        "pl+seed7",
        "pl+sisal",
        "pl+split-c",
        "pl+swift",
        "pl+unified-parallel-c",
        "pl+v",
        "pl+vala",
        "pl+verilog",
        "pl+whiley",
        "pl+wolfram",
        "pl+zig",
        "pl+zpl",
      ],
      influences: [
        "pl+algol",
        "pl+algol-60",
        "pl+algol-68",
        "pl+b",
        "pl+bcpl",
        "pl+cpl",
        "pl+fortran",
        "pl+fortran-95",
        "pl+pl-slashi",
        "pl+speedcoding",
      ],
      paradigms: ["para+imperative", "para+multi", "para+structured"],
      people: [["person+dennis-ritchie", "designer"]],
      platforms: ["platf+cross-platform"],
      typeSystems: ["tsys+manifest", "tsys+nominative", "tsys+static", "tsys+weak"],
    },
  );

  /**/

  lb.define(
    "pl+c99",
    "C99",
    { name: "C99", websites: [{ kind: "wikipedia", title: "C99", href: "https://en.wikipedia.org/wiki/C99" }] },
    { influenced: ["pl+opencl"], influences: ["pl+cpp"] },
  );

  /**/
}
