import type { PlangsGraph } from "../../entities/plangs_graph";

export function define(g: PlangsGraph) {
  const lb = g.plangBuilder;

  //-------------------------------------------------------------------------------

  lb.define(
    "pl+c",
    "C",
    {
      name: "C",
      websites: [
        { kind: "wikipedia", title: "C", href: "https://en.wikipedia.org/wiki/C_(programming_language)" },
        { kind: "homepage", title: "www.iso.org/standard/74528.html", href: "https://www.iso.org/standard/74528.html" },
        {
          kind: "homepage",
          title: "www.open-std.org/jtc1/sc22/wg14/",
          href: "http://www.open-std.org/jtc1/sc22/wg14/",
        },
        { kind: "wikipedia", title: "C", href: "https://en.wikipedia.org/wiki/List_of_C-based_programming_languages" },
      ],
      images: [
        {
          kind: "logo",
          url: "https://upload.wikimedia.org/wikipedia/commons/3/35/The_C_Programming_Language_logo.svg",
        },
      ],
      releases: [
        { version: "unknown", date: "1972-01-01", kind: "first" },
        { version: "unknown", date: "2018-01-01", kind: "stable" },
        { version: "unknown", date: "2024-02-21", kind: "preview" },
      ],
      references: {
        preview_release: [
          {
            href: "https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3221.htm",
            title: "N3221 - Editor's Report, Post January 2024 Strasbourg France Meeting",
          },
        ],
        influenced: [
          {
            href: "https://web.archive.org/web/20131106064022/http://cs.anu.edu.au/courses/ENGN3213/lectures/lecture6_VERILOG_2010.pdf",
            title: "Verilog HDL (and C)",
          },
        ],
      },
      extensions: [".c", ".h"],
    },
    {
      dialects: [
        "pl+c-plus-plus",
        "pl+carbon",
        "pl+objective-c",
        "pl+opencl-apiopencl-c-slashc-plus-plus-and-c-plus-plus-for-opencl",
      ],
      implementations: [
        "pl+c-plus-plusbuilder",
        "pl+clang",
        "pl+gcc",
        "pl+intel-c",
        "pl+microsoft-visual-c-plus-plus",
        "pl+pcc",
        "pl+watcom-c",
      ],
      influenced: [
        "pl+alef",
        "pl+algol",
        "pl+algol-60",
        "pl+ampl",
        "pl+awk",
        "pl+b",
        "pl+bcpl",
        "pl+bs",
        "pl+c--",
        "pl+c-plus-plus",
        "pl+cg-slashhlsl",
        "pl+chapel",
        "pl+charm",
        "pl+cilkopencilkcilk-plus",
        "pl+claire",
        "pl+crystal",
        "pl+cyclone",
        "pl+cython",
        "pl+d-programming-language",
        "pl+dart",
        "pl+draco",
        "pl+ec",
        "pl+ecmascript",
        "pl+embeddable-common-lisp",
        "pl+fortran",
        "pl+freebasic",
        "pl+go",
        "pl+godot-enginegdscript",
        "pl+handel-c",
        "pl+js-plus-plus",
        "pl+limbo",
        "pl+newlisp",
        "pl+newsqueak",
        "pl+objective-c",
        "pl+ocaml",
        "pl+pcastl",
        "pl+perl",
        "pl+php",
        "pl+pike",
        "pl+promal",
        "pl+python",
        "pl+quakec",
        "pl+rapid",
        "pl+ratfor",
        "pl+ring",
        "pl+s",
        "pl+sac",
        "pl+seed7",
        "pl+sisal",
        "pl+speedcoding",
        "pl+split-c",
        "pl+swift",
        "pl+transaction-programming-language-(tal)",
        "pl+unified-parallel-c-(upc)",
        "pl+vala",
        "pl+verilog",
        "pl+whiley",
        "pl+wolfram-language",
        "pl+zpl",
      ],
      influences: [
        "pl+algol-68",
        "pl+ampl",
        "pl+awk",
        "pl+b",
        "pl+bcpl",
        "pl+c--",
        "pl+c-plus-plus",
        "pl+c-sharp",
        "pl+cpl",
        "pl+csh",
        "pl+d",
        "pl+fortran",
        "pl+go",
        "pl+java",
        "pl+javascript",
        "pl+js-plus-plus",
        "pl+julia",
        "pl+limbo",
        "pl+lpc",
        "pl+nim",
        "pl+numerous",
        "pl+objective-c",
        "pl+perl",
        "pl+php",
        "pl+pike",
        "pl+pl-slashi",
        "pl+processing",
        "pl+python",
        "pl+rust",
        "pl+seed7",
        "pl+v-(vlang)",
        "pl+vala",
        "pl+verilog",
        "pl+zig",
      ],
      paradigms: ["para+imperative", "para+multi-paradigm", "para+structured"],
      people: [["person+dennis-ritchie", "designer"]],
      platforms: ["platf+cross-platform"],
      typeSystems: ["tsys+manifest", "tsys+nominative", "tsys+static", "tsys+weak"],
    },
  );
}
