import type { PlangsGraph } from "../../entities/plangs_graph";

export function define(g: PlangsGraph) {
  const lb = g.plangBuilder;

  //-------------------------------------------------------------------------------

  lb.define(
    "pl+lisp",
    "Lisp",
    {
      name: "Lisp",
      websites: [
        { kind: "wikipedia", title: "Lisp", href: "https://en.wikipedia.org/wiki/Lisp_(programming_language)" },
        { kind: "wikipedia", title: "Lisp", href: "https://en.wikipedia.org/wiki/Lisp_programming_language" },
      ],
      images: [{ kind: "logo", url: "https://upload.wikimedia.org/wikipedia/commons/4/48/Lisp_logo.svg" }],
      releases: [{ version: "unknown", date: "1960-01-01", kind: "first" }],
      references: {
        influenced: [
          {
            href: "https://web.archive.org/web/20160408134008/http://julia.readthedocs.org/en/latest/manual/introduction/",
            title: "Introduction",
          },
          { href: "https://www.wolfram.com/language/faq/", title: "Wolfram Language Q&A" },
        ],
      },
    },
    {
      dialects: [
        "pl+-starlisp-(starlisp)",
        "pl+allegro-common-lisp",
        "pl+arc",
        "pl+autolisp",
        "pl+clojure",
        "pl+common-lisp",
        "pl+cowsel--pop-1",
        "pl+emacs-lisp",
        "pl+embeddable-common-lisp",
        "pl+eulisp",
        "pl+franz-lisp",
        "pl+gambit",
        "pl+game-oriented-assembly-lisp",
        "pl+gnu-guile",
        "pl+hy",
        "pl+interlisp",
        "pl+islisp",
        "pl+kawa",
        "pl+le-lisp",
        "pl+lfe",
        "pl+lisp-machine-lisp",
        "pl+lispworks",
        "pl+logo",
        "pl+maclisp",
        "pl+mdl",
        "pl+multilisp",
        "pl+netlogo",
        "pl+newlisp",
        "pl+openlisp",
        "pl+pico",
        "pl+picolisp",
        "pl+pop-11",
        "pl+pop-2",
        "pl+racket",
        "pl+scheme",
        "pl+scm",
        "pl+siod",
        "pl+starlogo",
        "pl+t",
        "pl+ucblogo",
      ],
      influenced: [
        "pl+-starlisp-(starlisp)",
        "pl+agentcubes",
        "pl+agentsheets",
        "pl+allegro-common-lisp",
        "pl+amiga-e",
        "pl+arc",
        "pl+autolisp",
        "pl+ceylon",
        "pl+claire",
        "pl+clu",
        "pl+common-lisp",
        "pl+cowsel--pop-1",
        "pl+curl",
        "pl+embeddable-common-lisp",
        "pl+erlang",
        "pl+factor",
        "pl+franz-lisp",
        "pl+gambit",
        "pl+game-oriented-assembly-lisp",
        "pl+gnu-guile",
        "pl+haskell",
        "pl+information-processing-language-(ipl)",
        "pl+interlisp",
        "pl+io",
        "pl+iswim",
        "pl+java",
        "pl+julia",
        "pl+kawa",
        "pl+le-lisp",
        "pl+lisp-machine-lisp",
        "pl+lispworks",
        "pl+little-b",
        "pl+logo",
        "pl+mdl",
        "pl+multilisp",
        "pl+nemerle",
        "pl+nial",
        "pl+nim",
        "pl+nu",
        "pl+openlisp",
        "pl+oz",
        "pl+perl",
        "pl+pop-2",
        "pl+postscript",
        "pl+pure",
        "pl+python",
        "pl+r",
        "pl+rebol",
        "pl+red",
        "pl+rpl",
        "pl+ruby",
        "pl+scheme",
        "pl+scm",
        "pl+siod",
        "pl+smalltalk",
        "pl+squeak",
        "pl+tcl",
        "pl+ucblogo",
        "pl+visualworks",
        "pl+webassembly",
        "pl+wolfram-language",
      ],
      influences: [
        "pl+11",
        "pl+clips",
        "pl+clu",
        "pl+cowsel",
        "pl+dylan",
        "pl+elixir",
        "pl+excel",
        "pl+forth",
        "pl+haskell",
        "pl+information-processing-language",
        "pl+io",
        "pl+javascript",
        "pl+julia",
        "pl+logo",
        "pl+lua",
        "pl+ml",
        "pl+nim",
        "pl+nu",
        "pl+ops5",
        "pl+perl",
        "pl+pop-2",
        "pl+python",
        "pl+r",
        "pl+rebol",
        "pl+red",
        "pl+ruby",
        "pl+scala",
        "pl+smalltalk",
        "pl+swift",
        "pl+tcl",
        "pl+wolfram-language",
      ],
      paradigms: ["para+functional", "para+imperative", "para+meta", "para+multi-paradigm", "para+reflective"],
      people: [
        ["person+john-mccarthy", "designer"],
        ["person+steve-russell", "designer"],
      ],
      typeSystems: ["tsys+dynamic", "tsys+strong"],
    },
  );
}
