import type { PlangsGraph } from "../../entities/plangs_graph";

export function define(g: PlangsGraph) {
  const lb = g.plangBuilder;

  lb.define(
    "pl+pascal",
    "Pascal",
    {
      name: "Pascal",
      websites: [
        { kind: "wikipedia", title: "Pascal", href: "https://en.wikipedia.org/wiki/Pascal_(programming_language)" },
      ],
      releases: [{ version: "unknown", date: "1970-01-01", kind: "first" }],
      references: {
        influenced: [
          {
            href: "https://web.archive.org/web/20120627043929/http://java.sun.com/docs/white/delegates.html",
            title: 'About Microsoft\'s "Delegates"',
          },
          {
            href: "https://web.archive.org/web/20101229090912/http://www.fscript.org/prof/javapassport.pdf",
            title: "History of Java",
          },
          {
            href: "https://web.archive.org/web/20150716194245/http://queue.acm.org/detail.cfm?id=1017013",
            title: "A Conversation with James Gosling – ACM Queue",
          },
        ],
      },
    },
    {
      dialects: ["pl+ada", "pl+clarion", "pl+concurrent-pascal", "pl+object-pascal", "pl+planc"],
      implementations: [
        "pl+berkeley-software-distribution",
        "pl+cdc-6000",
        "pl+delphi",
        "pl+free-pascal",
        "pl+gnu-pascal",
        "pl+ibm-system-slash370",
        "pl+ict-1900-series",
        "pl+pascal-p",
        "pl+pdp-10",
        "pl+pdp-11",
        "pl+vsi-pascal",
      ],
      influenced: [
        "pl+a-",
        "pl+ada",
        "pl+aldor",
        "pl+algol",
        "pl+algol-60",
        "pl+algol-w",
        "pl+c-slashal",
        "pl+charm",
        "pl+comal",
        "pl+component-pascal",
        "pl+concurrent-pascal",
        "pl+draco",
        "pl+emerald",
        "pl+euclid",
        "pl+go",
        "pl+hypertalk",
        "pl+karel",
        "pl+kuka-robot-language",
        "pl+limbo",
        "pl+modula",
        "pl+modula-2",
        "pl+modula-2-plus",
        "pl+modula-3",
        "pl+ms-power-fx",
        "pl+object-pascal",
        "pl+ocaml",
        "pl+parasail",
        "pl+pascal-script",
        "pl+seed7",
        "pl+simula-67",
        "pl+sisal",
        "pl+sml",
        "pl+verilog",
        "pl+vhdl",
        "pl+wolfram-language",
        "pl+zonnon",
      ],
      influences: [
        "pl+ada",
        "pl+algol-w",
        "pl+c-sharp",
        "pl+c-slashal",
        "pl+component-pascal",
        "pl+go",
        "pl+java",
        "pl+modula",
        "pl+modula-2",
        "pl+modula-3",
        "pl+ms-power-fx",
        "pl+oberon",
        "pl+oberon-2",
        "pl+object-pascal",
        "pl+oxygene",
        "pl+seed7",
        "pl+simula",
        "pl+sml",
        "pl+structured-text",
        "pl+vhdl",
      ],
      paradigms: ["para+imperative", "para+structured"],
      people: [["person+niklaus-wirth", "designer"]],
      typeSystems: ["tsys+safe", "tsys+static", "tsys+strong"],
    },
  );

  /**/
}
