import type { PlangsGraph } from "NaNentities/plangs_graph";

export function define(g: PlangsGraph) {
  const lb = g.plangBuilder;

  lb.define(
    "pl+smalltalk",
    "Smalltalk",
    {
      name: "Smalltalk",
      websites: [{ kind: "wikipedia", title: "Smalltalk", href: "https://en.wikipedia.org/wiki/Smalltalk" }],
      images: [{ kind: "logo", url: "https://upload.wikimedia.org/wikipedia/commons/b/bf/Smalltalk_Balloon.svg" }],
      releases: [
        { version: "unknown", date: "1972-01-01", kind: "first" },
        { version: "unknown", date: "1980-01-01", kind: "stable" },
      ],
      references: {
        platform: [
          { href: "http://bitsavers.org/pdf/xerox/alto/schematics/AltoI_Schematics.pdf", title: "Alto I Schematics" },
          {
            href: "http://history-computer.com/ModernComputer/Personal/Alto.html",
            title: "History of Computers and Computing, Birth of the modern computer, Personal computer, Xerox Alto",
          },
        ],
        influenced_by: [
          { href: "http://www.purl.org/stefan_ram/pub/doc_kay_oop_en", title: "E-Mail of 2003-07-23" },
          {
            href: "http://gagne.homedns.org/~tgagne/contrib/EarlyHistoryST.html",
            title: "The Early History of Smalltalk",
          },
        ],
      },
    },
    {
      dialects: ["pl+dolphin-smalltalk", "pl+newspeak", "pl+pharo", "pl+self", "pl+strongtalk"],
      implementations: [
        "pl+amber",
        "pl+dolphin-smalltalk",
        "pl+gemstone-slashs",
        "pl+gnu-smalltalk",
        "pl+pharo",
        "pl+squeak",
        "pl+va-smalltalk",
        "pl+visualworks",
      ],
      influenced: [
        "pl+ada",
        "pl+agentcubes",
        "pl+agentsheets",
        "pl+ambienttalk",
        "pl+c-plus-plus",
        "pl+ceylon",
        "pl+claire",
        "pl+cobol",
        "pl+dart",
        "pl+dolphin-smalltalk",
        "pl+emerald",
        "pl+erlang",
        "pl+etoys",
        "pl+gemstone-slashs-object-server",
        "pl+go",
        "pl+groovy",
        "pl+io",
        "pl+java",
        "pl+lasso",
        "pl+lisp",
        "pl+logo",
        "pl+logtalk",
        "pl+mdl",
        "pl+newspeak",
        "pl+oaklisp",
        "pl+object-pascal",
        "pl+object-rexx",
        "pl+objective-c",
        "pl+orc",
        "pl+pharo",
        "pl+pico",
        "pl+planner",
        "pl+raku",
        "pl+ruby",
        "pl+scala",
        "pl+scratch",
        "pl+self",
        "pl+simula",
        "pl+snap-",
        "pl+squeak",
        "pl+strongtalk",
        "pl+ucblogo",
        "pl+wolfram-language",
        "pl+xtend",
      ],
      influences: [
        "pl+applescript",
        "pl+arpanet",
        "pl+burroughs-b5000",
        "pl+common-lisp-object-system",
        "pl+dart",
        "pl+dylan",
        "pl+erlang",
        "pl+etoys",
        "pl+euler",
        "pl+go",
        "pl+groovy",
        "pl+imp",
        "pl+io",
        "pl+java",
        "pl+lasso",
        "pl+lisp",
        "pl+logo",
        "pl+logtalk",
        "pl+newspeak",
        "pl+newtonscript",
        "pl+object-rexx",
        "pl+objective-c",
        "pl+php",
        "pl+planner",
        "pl+python",
        "pl+raku",
        "pl+ruby",
        "pl+scala",
        "pl+scratch",
        "pl+self",
        "pl+simula",
        "pl+sketchpad",
        "pl+swift",
      ],
      paradigms: ["para+objects"],
      people: [
        ["person+adele-goldberg", "designer"],
        ["person+alan-kay", "designer"],
        ["person+dan-ingalls", "designer"],
        ["person+diana-merry", "designer"],
        ["person+peter-deutsch", "designer"],
        ["person+ted-kaehler", "designer"],
      ],
      platforms: ["platf+74181", "platf+cross-platform"],
      typeSystems: ["tsys+dynamic", "tsys+object-oriented", "tsys+strong"],
    },
  );

  /**/
}
