const PV_APL                        = 'pl+APL';                         //  1966-11-27 - https://en.wikipedia.org/wiki/APL_(programming_language) _ https://aplwiki.com/
const PV_Agda                       = 'pl+Agda';                        //  2007-01-01 - https://en.wikipedia.org/wiki/Agda_(programming_language) _ https://en.wikipedia.org/wiki/Agda_(theorem_prover) _ http://wiki.portal.chalmers.se/agda
const PV_Arc                        = 'pl+Arc';                         //  2008-01-29 - https://en.wikipedia.org/wiki/Arc_(programming_language) _ http://arclanguage.org
const PV_AssemblyScript             = 'pl+AssemblyScript';              //  0000-00-00 - https://en.wikipedia.org/wiki/AssemblyScript
const PV_Ballerina                  = 'pl+Ballerina';                   //  2017-01-01 - https://en.wikipedia.org/wiki/Ballerina_(programming_language) _ http://ballerina.io/
const PV_Bash                       = 'pl+Bash';                        //  1989-01-01 - https://en.wikipedia.org/wiki/Bash_(Unix_shell) _ https://www.gnu.org/software/bash/
const PV_Basic                      = 'pl+Basic';                       //  0000-00-00 - https://en.wikipedia.org/wiki/BASIC
const PV_Blockly                    = 'pl+Blockly';                     //  2012-01-01 - https://en.wikipedia.org/wiki/Blockly _ http://developers.google.com/blockly
const PV_Boomerang                  = 'pl+Boomerang';                   //  2008-01-01 - https://en.wikipedia.org/wiki/Boomerang_(programming_language) _ http://www.seas.upenn.edu/~harmony/
const PV_Bosque                     = 'pl+Bosque';                      //  2019-03-03 - https://en.wikipedia.org/wiki/Bosque_(programming_language) _ https://www.microsoft.com/en-us/research/project/bosque-programming-language/
const PV_Bourne_shell               = 'pl+Bourne-shell';                //  0000-00-00 - https://en.wikipedia.org/wiki/Bourne_shell
const PV_Brainfuck                  = 'pl+Brainfuck';                   //  1993-01-01 - https://en.wikipedia.org/wiki/Brainfuck
const PV_C                          = 'pl+C';                           //  1972-01-01 - https://en.wikipedia.org/wiki/C_(programming_language) _ https://www.iso.org/standard/74528.html _ http://www.open-std.org/jtc1/sc22/wg14/
const PV_C99                        = 'pl+C99';                         //  0000-00-00 - https://en.wikipedia.org/wiki/C99
const PV_CLOS                       = 'pl+CLOS';                        //  0000-00-00 - https://en.wikipedia.org/wiki/Common_Lisp_Object_System
const PV_CPP                        = 'pl+CPP';                         //  1985-01-01 - https://en.wikipedia.org/wiki/C%2B%2B _ https://isocpp.org/
const PV_CPython                    = 'pl+CPython';                     //  1994-01-26 - https://en.wikipedia.org/wiki/CPython _ https://www.python.org/
const PV_CSP                        = 'pl+CSP';                         //  0000-00-00 - https://en.wikipedia.org/wiki/Communicating_sequential_processes
const PV_CSharp                     = 'pl+CSharp';                      //  0000-00-00 - https://en.wikipedia.org/wiki/C_Sharp_(programming_language)
const PV_Carbon                     = 'pl+Carbon';                      //  0000-00-00 - https://en.wikipedia.org/wiki/Carbon_(programming_language) _ https://github.com/carbon-language
const PV_Ceylon                     = 'pl+Ceylon';                      //  2011-01-01 - https://en.wikipedia.org/wiki/Ceylon_(programming_language) _ http://ceylon-lang.org
const PV_ChucK                      = 'pl+ChucK';                       //  2003-01-01 - https://en.wikipedia.org/wiki/ChucK _ http://chuck.cs.princeton.edu
const PV_Ciao                       = 'pl+Ciao';                        //  1984-01-01 - https://en.wikipedia.org/wiki/Ciao_(programming_language) _ http://www.ciao-lang.org
const PV_Clang                      = 'pl+Clang';                       //  2007-09-26 - https://en.wikipedia.org/wiki/Clang _ https://clang.llvm.org
const PV_Clojure                    = 'pl+Clojure';                     //  2007-01-01 - https://en.wikipedia.org/wiki/Clojure _ https://clojure.org
const PV_ClojureScript              = 'pl+ClojureScript';               //  0000-00-00 - undefined
const PV_CoffeeScript               = 'pl+CoffeeScript';                //  0000-00-00 - https://en.wikipedia.org/wiki/CoffeeScript
const PV_Common_Lisp                = 'pl+Common-Lisp';                 //  0000-00-00 - https://en.wikipedia.org/wiki/Common_Lisp
const PV_Common_Lisp_Object_System  = 'pl+Common-Lisp-Object-System';   //  0000-00-00 - https://en.wikipedia.org/wiki/Common_Lisp_Object_System
const PV_Coq                        = 'pl+Coq';                         //  0000-00-00 - https://en.wikipedia.org/wiki/Coq_(software)
const PV_Cryptol                    = 'pl+Cryptol';                     //  0000-00-00 - https://en.wikipedia.org/wiki/Cryptol _ https://galoisinc.github.io/cryptol/master/RefMan.html
const PV_Crystal                    = 'pl+Crystal';                     //  2014-06-19 - https://en.wikipedia.org/wiki/Crystal_(programming_language) _ https://crystal-lang.org
const PV_Csound                     = 'pl+Csound';                      //  1986-01-01 - https://en.wikipedia.org/wiki/Csound _ http://csound.com
const PV_Cython                     = 'pl+Cython';                      //  2007-07-28 - https://en.wikipedia.org/wiki/Cython _ https://cython.org
const PV_Dart                       = 'pl+Dart';                        //  2011-10-10 - https://en.wikipedia.org/wiki/Dart_(programming_language) _ https://dart.dev
const PV_DataFlex                   = 'pl+DataFlex';                    //  2024-03-13 - https://en.wikipedia.org/wiki/Visual_DataFlex _ http://www.DataAccess.com/DataFlex
const PV_Datalog                    = 'pl+Datalog';                     //  1977-01-01 - https://en.wikipedia.org/wiki/Datalog
const PV_Delphi                     = 'pl+Delphi';                      //  1995-01-01 - https://en.wikipedia.org/wiki/Delphi_(software) _ https://www.embarcadero.com/products/delphi
const PV_Dylan                      = 'pl+Dylan';                       //  1992-01-01 - https://en.wikipedia.org/wiki/Dylan_(programming_language) _ https://opendylan.org/
const PV_ECMAScript                 = 'pl+ECMAScript';                  //  1997-01-01 - https://en.wikipedia.org/wiki/ECMAScript _ https://www.ecma-international.org/publications-and-standards/standards/
const PV_Elixir                     = 'pl+Elixir';                      //  2012-01-01 - https://en.wikipedia.org/wiki/Elixir_(programming_language) _ https://elixir-lang.org
const PV_Elm                        = 'pl+Elm';                         //  2012-03-30 - https://en.wikipedia.org/wiki/Elm_(programming_language) _ https://elm-lang.org/
const PV_Emacs_Lisp                 = 'pl+Emacs-Lisp';                  //  1985-01-01 - https://en.wikipedia.org/wiki/Emacs_Lisp _ http://www.gnu.org/software/emacs
const PV_Erlang                     = 'pl+Erlang';                      //  1986-01-01 - https://en.wikipedia.org/wiki/Erlang_(programming_language) _ https://www.erlang.org
const PV_Euphoria                   = 'pl+Euphoria';                    //  1993-01-01 - https://en.wikipedia.org/wiki/Euphoria_(programming_language) _ http://openeuphoria.org
const PV_FAUST                      = 'pl+FAUST';                       //  2002-01-01 - https://en.wikipedia.org/wiki/FAUST_(programming_language) _ http://faust.grame.fr
const PV_FSharp                     = 'pl+FSharp';                      //  0000-00-00 - https://en.wikipedia.org/wiki/F_Sharp_(programming_language)
const PV_Factor                     = 'pl+Factor';                      //  2003-01-01 - https://en.wikipedia.org/wiki/Factor_(programming_language) _ http://factorcode.org/
const PV_Fantom                     = 'pl+Fantom';                      //  2005-01-01 - https://en.wikipedia.org/wiki/Fantom_(programming_language) _ http://www.fantom.org
const PV_Flix                       = 'pl+Flix';                        //  0000-00-00 - https://en.wikipedia.org/wiki/Flix_(programming_language) _ https://flix.dev/
const PV_Forth                      = 'pl+Forth';                       //  1970-01-01 - https://en.wikipedia.org/wiki/Forth_(programming_language) _ https://forth-standard.org
const PV_Fortran                    = 'pl+Fortran';                     //  1957-01-01 - https://en.wikipedia.org/wiki/Fortran _ https://en.wikipedia.org/wiki/Fortran_95 _ https://fortran-lang.org
const PV_FreeBASIC                  = 'pl+FreeBASIC';                   //  2004-01-01 - https://en.wikipedia.org/wiki/FreeBASIC _ http://www.freebasic.net
const PV_Futhark                    = 'pl+Futhark';                     //  2014-01-01 - https://en.wikipedia.org/wiki/Futhark_(programming_language) _ http://futhark-lang.org
const PV_GDScript                   = 'pl+GDScript';                    //  0000-00-00 - https://en.wikipedia.org/wiki/Godot_(game_engine)#GDScript
const PV_GLSL                       = 'pl+GLSL';                        //  0000-00-00 - https://en.wikipedia.org/wiki/GLSL
const PV_GNAT                       = 'pl+GNAT';                        //  1995-01-01 - https://en.wikipedia.org/wiki/GNAT _ http://www.getadanow.com _ http://www.adacore.com/gnatpro/
const PV_GNU_Awk_gawk               = 'pl+GNU-Awk-gawk';                //  0000-00-00 - undefined
const PV_GNU_Guile                  = 'pl+GNU-Guile';                   //  1993-01-01 - https://en.wikipedia.org/wiki/GNU_Guile _ https://gnu.org/software/guile
const PV_GNU_Octave                 = 'pl+GNU-Octave';                  //  1993-01-01 - https://en.wikipedia.org/wiki/GNU_Octave _ https://gnu.org/software/octave/
const PV_GNU_Prolog                 = 'pl+GNU-Prolog';                  //  2021-07-08 - https://en.wikipedia.org/wiki/GNU_Prolog _ http://www.gprolog.org
const PV_Gambit                     = 'pl+Gambit';                      //  1988-01-01 - https://en.wikipedia.org/wiki/Gambit_(Scheme_implementation) _ http://gambitscheme.org
const PV_Gforth                     = 'pl+Gforth';                      //  1992-01-01 - https://en.wikipedia.org/wiki/Gforth _ http://gnu.org/s/gforth/
const PV_Gleam                      = 'pl+Gleam';                       //  2016-06-13 - https://en.wikipedia.org/wiki/Gleam_(programming_language) _ https://gleam.run/
const PV_Go                         = 'pl+Go';                          //  2009-11-10 - https://en.wikipedia.org/wiki/Go_(programming_language) _ https://go.dev
const PV_Gosu                       = 'pl+Gosu';                        //  2024-01-01 - https://en.wikipedia.org/wiki/Gosu_(programming_language) _ https://gosu-lang.github.io/
const PV_Groovy                     = 'pl+Groovy';                      //  2003-01-01 - https://en.wikipedia.org/wiki/Groovy_(programming_language) _ https://en.wikipedia.org/wiki/Apache_Groovy _ https://groovy-lang.org
const PV_Guile                      = 'pl+Guile';                       //  0000-00-00 - https://en.wikipedia.org/wiki/GNU_Guile
const PV_Hack                       = 'pl+Hack';                        //  2014-01-01 - https://en.wikipedia.org/wiki/Hack_(programming_language) _ https://hacklang.org/
const PV_Haskell                    = 'pl+Haskell';                     //  1990-01-01 - https://en.wikipedia.org/wiki/Haskell_(programming_language) _ http://haskell.org
const PV_Haxe                       = 'pl+Haxe';                        //  2005-11-14 - https://en.wikipedia.org/wiki/Haxe _ https://haxe.org
const PV_HotSpot                    = 'pl+HotSpot';                     //  0000-00-00 - https://en.wikipedia.org/wiki/HotSpot_(virtual_machine)
const PV_Hy                         = 'pl+Hy';                          //  2013-01-01 - https://en.wikipedia.org/wiki/Hy_(programming_language) _ http://hylang.org
const PV_HyperCard                  = 'pl+HyperCard';                   //  1987-01-01 - https://en.wikipedia.org/wiki/HyperCard
const PV_HyperTalk                  = 'pl+HyperTalk';                   //  1987-01-01 - https://en.wikipedia.org/wiki/HyperTalk
const PV_Idris                      = 'pl+Idris';                       //  2007-01-01 - https://en.wikipedia.org/wiki/Idris_(programming_language) _ http://idris-lang.org
const PV_Inform                     = 'pl+Inform';                      //  0000-00-00 - https://en.wikipedia.org/wiki/Inform
const PV_Io                         = 'pl+Io';                          //  2002-01-01 - https://en.wikipedia.org/wiki/Io_(programming_language) _ https://iolanguage.org/
const PV_IronPython                 = 'pl+IronPython';                  //  2006-09-05 - https://en.wikipedia.org/wiki/IronPython _ https://ironpython.net
const PV_J                          = 'pl+J';                           //  1990-01-01 - https://en.wikipedia.org/wiki/J_(programming_language) _ http://www.jsoftware.com
const PV_JRuby                      = 'pl+JRuby';                       //  2001-01-01 - https://en.wikipedia.org/wiki/JRuby _ https://www.jruby.org
const PV_JSON                       = 'pl+JSON';                        //  0000-00-00 - https://en.wikipedia.org/wiki/JSON
const PV_Java                       = 'pl+Java';                        //  1995-05-23 - https://en.wikipedia.org/wiki/Java_(programming_language) _ http://oracle.com/java/ _ http://java.com _ http://dev.java
const PV_JavaScript                 = 'pl+JavaScript';                  //  1995-12-04 - https://en.wikipedia.org/wiki/JavaScript _ https://en.wikipedia.org/wiki/Javascript_(programming_language) _ https://ecma-international.org/publications-and-standards/standards/ecma-262/
const PV_Julia                      = 'pl+Julia';                       //  2012-01-01 - https://en.wikipedia.org/wiki/Julia_(programming_language) _ https://JuliaLang.org
const PV_K                          = 'pl+K';                           //  1993-01-01 - https://en.wikipedia.org/wiki/K_(programming_language) _ http://kx.com
const PV_Korn_Shell                 = 'pl+Korn-Shell';                  //  0000-00-00 - https://en.wikipedia.org/wiki/KornShell
const PV_Kotlin                     = 'pl+Kotlin';                      //  2011-07-22 - https://en.wikipedia.org/wiki/Kotlin_(programming_language) _ https://kotlinlang.org/
const PV_LFE                        = 'pl+LFE';                         //  2008-01-01 - https://en.wikipedia.org/wiki/LFE_(programming_language) _ http://lfe.io
const PV_LabVIEW                    = 'pl+LabVIEW';                     //  1986-01-01 - https://en.wikipedia.org/wiki/LabVIEW _ https://www.ni.com/labview
const PV_Lean                       = 'pl+Lean';                        //  2013-01-01 - https://en.wikipedia.org/wiki/Lean_(proof_assistant) _ https://lean-lang.org/
const PV_Lisp                       = 'pl+Lisp';                        //  1960-01-01 - https://en.wikipedia.org/wiki/Lisp_(programming_language) _ https://en.wikipedia.org/wiki/Lisp_programming_language
const PV_LiveCode                   = 'pl+LiveCode';                    //  0000-00-00 - https://en.wikipedia.org/wiki/LiveCode
const PV_LiveScript                 = 'pl+LiveScript';                  //  2011-01-01 - https://en.wikipedia.org/wiki/LiveScript_(programming_language) _ https://livescript.net
const PV_Logo                       = 'pl+Logo';                        //  1967-01-01 - https://en.wikipedia.org/wiki/Logo_(programming_language) _ https://en.wikipedia.org/wiki/ObjectLOGO
const PV_Lua                        = 'pl+Lua';                         //  1993-01-01 - https://en.wikipedia.org/wiki/Lua_(programming_language) _ https://www.lua.org/
const PV_MATLAB                     = 'pl+MATLAB';                      //  0000-00-00 - https://en.wikipedia.org/wiki/MATLAB
const PV_ML                         = 'pl+ML';                          //  1973-01-01 - https://en.wikipedia.org/wiki/ML_(programming_language)
const PV_Magma                      = 'pl+Magma';                       //  2023-02-22 - https://en.wikipedia.org/wiki/Magma_computer_algebra_system _ http://magma.maths.usyd.edu.au
const PV_Maple                      = 'pl+Maple';                       //  1982-01-01 - https://en.wikipedia.org/wiki/Maple_(software) _ https://www.maplesoft.com/products/Maple/
const PV_Max                        = 'pl+Max';                         //  2024-01-01 - https://en.wikipedia.org/wiki/Max_(software) _ https://cycling74.com/products/max/
const PV_Maxima                     = 'pl+Maxima';                      //  1982-01-01 - https://en.wikipedia.org/wiki/Maxima_(software) _ https://maxima.sourceforge.io/
const PV_Mercury                    = 'pl+Mercury';                     //  1995-04-08 - https://en.wikipedia.org/wiki/Mercury_(programming_language) _ http://www.mercurylang.org
const PV_Microsoft_Basic            = 'pl+Microsoft-Basic';             //  0000-00-00 - https://en.wikipedia.org/wiki/Microsoft_BASIC
const PV_Modelica                   = 'pl+Modelica';                    //  1997-01-01 - https://en.wikipedia.org/wiki/Modelica _ https://www.modelica.org/
const PV_Mojo                       = 'pl+Mojo';                        //  2023-01-01 - https://en.wikipedia.org/wiki/Mojo_(programming_language) _ https://www.modular.com/mojo
const PV_NekoVM                     = 'pl+NekoVMNeko';                  //  2005-01-01 - https://en.wikipedia.org/wiki/Neko_(programming_language) _ http://nekovm.org/specs/syntax
const PV_Nim                        = 'pl+Nim';                         //  2008-01-01 - https://en.wikipedia.org/wiki/Nim_(programming_language) _ http://nim-lang.org
const PV_OCaml                      = 'pl+OCaml';                       //  1996-01-01 - https://en.wikipedia.org/wiki/OCaml _ https://ocaml.org/
const PV_Oberon                     = 'pl+Oberon';                      //  1987-01-01 - https://en.wikipedia.org/wiki/Oberon_(programming_language) _ https://projectoberon.net
const PV_Objective_C                = 'pl+Objective-C';                 //  0000-00-00 - https://en.wikipedia.org/wiki/Objective-C
const PV_OpenACC                    = 'pl+OpenACC';                     //  2021-01-01 - https://en.wikipedia.org/wiki/OpenACC _ https://www.openacc.org/
const PV_OpenMP                     = 'pl+OpenMP';                      //  2021-01-01 - https://en.wikipedia.org/wiki/OpenMP _ http://openmp.org
const PV_P4                         = 'pl+P4';                          //  2013-01-01 - https://en.wikipedia.org/wiki/P4_(programming_language) _ https://p4.org
const PV_PARIslashGP                = 'pl+PARISlashGP';                 //  2024-01-01 - https://en.wikipedia.org/wiki/PARI/GP _ http://pari.math.u-bordeaux.fr/
const PV_PHP                        = 'pl+PHP';                         //  1995-06-08 - https://en.wikipedia.org/wiki/PHP _ https://thephp.foundation
const PV_PLslashpgSQL               = 'pl+PLSlashpgSQL';                //  1998-10-30 - https://en.wikipedia.org/wiki/PL/pgSQL _ https://www.postgresql.org/docs/current/static/plpgsql.html
const PV_POV_Ray                    = 'pl+POV-Ray';                     //  1991-07-29 - https://en.wikipedia.org/wiki/POV-Ray _ https://www.povray.org
const PV_Pascal                     = 'pl+Pascal';                      //  1970-01-01 - https://en.wikipedia.org/wiki/Pascal_(programming_language)
const PV_PeachPie                   = 'pl+PeachPie';                    //  2016-07-18 - https://en.wikipedia.org/wiki/PeachPie _ http://www.peachpie.io
const PV_Perl                       = 'pl+Perl';                        //  1987-12-18 - https://en.wikipedia.org/wiki/Perl _ https://www.perl.org/
const PV_Pharo                      = 'pl+Pharo';                       //  2008-01-01 - https://en.wikipedia.org/wiki/Pharo _ http://pharo.org
const PV_Picolisp                   = 'pl+Picolisp';                    //  0000-00-00 - https://en.wikipedia.org/wiki/Picolisp
const PV_PostScript                 = 'pl+PostScript';                  //  1982-01-01 - https://en.wikipedia.org/wiki/PostScript
const PV_PowerBASIC                 = 'pl+PowerBASIC';                  //  1989-01-01 - https://en.wikipedia.org/wiki/PowerBASIC _ https://www.powerbasic.com/
const PV_PowerShell                 = 'pl+PowerShell';                  //  2006-11-14 - https://en.wikipedia.org/wiki/Windows_PowerShell _ https://en.wikipedia.org/wiki/PowerShell _ https://microsoft.com/powershell
const PV_Processing                 = 'pl+Processing';                  //  0000-00-00 - https://en.wikipedia.org/wiki/Processing_(programming_language)
const PV_Prolog                     = 'pl+Prolog';                      //  1972-01-01 - https://en.wikipedia.org/wiki/Prolog _ https://www.iso.org/standard/21413.html _ https://www.iso.org/standard/20775.html
const PV_Pure                       = 'pl+Pure';                        //  2008-01-01 - https://en.wikipedia.org/wiki/Pure_(programming_language) _ https://agraef.github.io/pure-lang/
const PV_PureData                   = 'pl+PureData';                    //  0000-00-00 - https://en.wikipedia.org/wiki/PureData
const PV_PureScript                 = 'pl+PureScript';                  //  2013-01-01 - https://en.wikipedia.org/wiki/PureScript _ https://www.purescript.org/
const PV_Pyomo                      = 'pl+Pyomo';                       //  2008-01-01 - https://en.wikipedia.org/wiki/Pyomo _ https://www.pyomo.org
const PV_Python                     = 'pl+Python';                      //  1991-02-20 - https://en.wikipedia.org/wiki/Python_(programming_language) _ https://www.python.org/
const PV_Q                          = 'pl+Q';                           //  0000-00-00 - https://en.wikipedia.org/wiki/Q_(programming_language_from_Kx_Systems)
const PV_QB64                       = 'pl+QB64';                        //  2007-09-08 - https://en.wikipedia.org/wiki/QB64 _ http://www.qb64.com
const PV_QML                        = 'pl+QML';                         //  2009-01-01 - https://en.wikipedia.org/wiki/QML _ http://qt-project.org/doc/qt-5/qmlapplications.html
const PV_R                          = 'pl+R';                           //  1993-01-01 - https://en.wikipedia.org/wiki/R_(programming_language) _ https://www.r-project.org
const PV_Rebol                      = 'pl+Rebol';                       //  1997-01-01 - https://en.wikipedia.org/wiki/Rebol _ https://en.wikipedia.org/wiki/REBOL _ http://www.rebol.com
const PV_RPython                    = 'pl+RPython';                     //  0000-00-00 - https://en.wikipedia.org/wiki/PyPy#RPython
const PV_Racket                     = 'pl+Racket';                      //  1995-01-28 - https://en.wikipedia.org/wiki/Racket_(programming_language) _ https://racket-lang.org/
const PV_Raku                       = 'pl+Raku';                        //  2015-12-25 - https://en.wikipedia.org/wiki/Raku_(programming_language) _ http://raku.org
const PV_Rakudo                     = 'pl+Rakudo';                      //  2024-05-30 - https://en.wikipedia.org/wiki/Rakudo _ http://rakudo.org/
const PV_Reason                     = 'pl+Reason';                      //  2016-05-16 - https://en.wikipedia.org/wiki/Reason_(programming_language) _ https://reasonml.github.io/
const PV_Red                        = 'pl+Red';                         //  2011-01-01 - https://en.wikipedia.org/wiki/Red_(programming_language) _ https://www.red-lang.org/
const PV_Ring                       = 'pl+Ring';                        //  2016-01-25 - https://en.wikipedia.org/wiki/Ring_(programming_language) _ http://ring-lang.net
const PV_Ruby                       = 'pl+Ruby';                        //  1995-01-01 - https://en.wikipedia.org/wiki/Ruby_(programming_language) _ https://www.ruby-lang.org/en/
const PV_Rust                       = 'pl+Rust';                        //  2015-05-15 - https://en.wikipedia.org/wiki/Rust_(programming_language) _ https://foundation.rust-lang.org
const PV_SQL                        = 'pl+SQL';                         //  0000-00-00 - https://en.wikipedia.org/wiki/SQL
const PV_SWI_Prolog                 = 'pl+SWI-Prolog';                  //  1987-01-01 - https://en.wikipedia.org/wiki/SWI-Prolog _ http://swi-prolog.org
const PV_Scala                      = 'pl+Scala';                       //  2004-01-20 - https://en.wikipedia.org/wiki/Scala_(programming_language) _ http://www.scala-lang.org
const PV_Scheme                     = 'pl+Scheme';                      //  1975-01-01 - https://en.wikipedia.org/wiki/Scheme_(programming_language) _ https://www.scheme.org/
const PV_Scilab                     = 'pl+Scilab';                      //  2024-01-01 - https://en.wikipedia.org/wiki/Scilab _ https://www.scilab.org
const PV_Scratch                    = 'pl+Scratch';                     //  2003-10-11 - https://en.wikipedia.org/wiki/Scratch_(programming_language) _ https://scratch.mit.edu/
const PV_ScratchJr                  = 'pl+ScratchJr';                   //  2014-01-01 - https://en.wikipedia.org/wiki/ScratchJr _ http://www.scratchjr.org
const PV_Self                       = 'pl+Self';                        //  1987-01-01 - https://en.wikipedia.org/wiki/Self_(programming_language) _ http://www.selflanguage.org
const PV_SmallBASIC                 = 'pl+SmallBASIC';                  //  2024-04-26 - https://en.wikipedia.org/wiki/SmallBasic _ https://smallbasic.github.io
const PV_Smalltalk                  = 'pl+Smalltalk';                   //  1972-01-01 - https://en.wikipedia.org/wiki/Smalltalk
const PV_Solidity                   = 'pl+Solidity';                    //  2014-01-01 - https://en.wikipedia.org/wiki/Solidity _ https://soliditylang.org
const PV_Souffle                    = 'pl+Souffle';                     //  0000-00-00 - https://en.wikipedia.org/wiki/Souffl%C3%A9_(programming_language)
const PV_Source                     = 'pl+Source';                      //  2017-01-01 - https://en.wikipedia.org/wiki/Source_(programming_language) _ https://docs.sourceacademy.org/
const PV_Squeak                     = 'pl+Squeak';                      //  1996-01-01 - https://en.wikipedia.org/wiki/Squeak _ http://www.squeak.org
const PV_Standard_ML                = 'pl+Standard-ML';                 //  0000-00-00 - https://en.wikipedia.org/wiki/Standard_ML
const PV_Starlark                   = 'pl+Starlark';                    //  0000-00-00 - https://en.wikipedia.org/wiki/Bazel_(software)
const PV_Stateflow                  = 'pl+Stateflow';                   //  2018-09-12 - https://en.wikipedia.org/wiki/Stateflow _ http://www.mathworks.com/products/stateflow?s_cid=wiki_stateflow_2
const PV_SuperCollider              = 'pl+SuperCollider';               //  0000-00-00 - https://en.wikipedia.org/wiki/SuperCollider
const PV_Swift                      = 'pl+Swift';                       //  2007-01-01 - https://en.wikipedia.org/wiki/Swift_(parallel_scripting_language) _ http://swift-lang.org
const PV_SystemVerilog              = 'pl+SystemVerilog';               //  0000-00-00 - https://en.wikipedia.org/wiki/SystemVerilog
const PV_TXL                        = 'pl+TXL';                         //  0000-00-00 - https://en.wikipedia.org/wiki/TXL_(programming_language) _ https://www.txl.ca/
const PV_Tcl                        = 'pl+Tcl';                         //  1988-01-01 - https://en.wikipedia.org/wiki/Tcl _ https://www.tcl-lang.org _ https://www.tcl.tk
const PV_Tom                        = 'pl+Tom';                         //  2013-03-21 - https://en.wikipedia.org/wiki/Tom_(pattern_matching_language) _ http://tom.loria.fr
const PV_Turbo_Pascal               = 'pl+Turbo-Pascal';                //  0000-00-00 - https://en.wikipedia.org/wiki/Turbo_Pascal
const PV_TypeScript                 = 'pl+TypeScript';                  //  2012-10-01 - https://en.wikipedia.org/wiki/TypeScript _ https://www.typescriptlang.org
const PV_Umple                      = 'pl+Umple';                       //  2008-01-01 - https://en.wikipedia.org/wiki/Umple _ http://www.umple.org/
const PV_V                          = 'pl+V';                           //  2019-06-20 - https://en.wikipedia.org/wiki/V_(programming_language) _ http://vlang.io
const PV_VHDL                       = 'pl+VHDL';                        //  1980-01-01 - https://en.wikipedia.org/wiki/VHDL _ https://opensource.ieee.org/vasg
const PV_Vala                       = 'pl+Vala';                        //  2006-01-01 - https://en.wikipedia.org/wiki/Vala_(programming_language) _ https://vala.dev
const PV_Verilog                    = 'pl+Verilog';                     //  1984-01-01 - https://en.wikipedia.org/wiki/Verilog _ https://ieeexplore.ieee.org/document/10458102
const PV_Verse                      = 'pl+Verse';                       //  2023-01-01 - https://en.wikipedia.org/wiki/Verse_(programming_language) _ https://dev.epicgames.com/documentation/en-us/uefn/verse-language-reference
const PV_Visual_Basic               = 'pl+Visual-Basic';                //  0000-00-00 - https://en.wikipedia.org/wiki/Visual_Basic
const PV_VBdotnet                   = 'pl+Visual-Basic-dotNET';         //  0000-00-00 - https://en.wikipedia.org/wiki/Visual_Basic_.NET
const PV_Visual_CPP                 = 'pl+Visual-CPP';                  //  3381-01-01 - https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B _ https://docs.microsoft.com/en-us/cpp/
const PV_Whiley                     = 'pl+Whiley';                      //  2010-01-01 - https://en.wikipedia.org/wiki/Whiley_(programming_language) _ http://whiley.org
const PV_Wolfram                    = 'pl+Wolfram';                     //  0000-00-00 - https://en.wikipedia.org/wiki/Wolfram_Language
const PV_XAML                       = 'pl+XAML';                        //  0000-00-00 - https://en.wikipedia.org/wiki/XAML
const PV_XOD                        = 'pl+XOD';                         //  2016-01-01 - https://en.wikipedia.org/wiki/XOD_(programming_language) _ http://xod.io
const PV_XPath                      = 'pl+XPath';                       //  0000-00-00 - https://en.wikipedia.org/wiki/XPath
const PV_XQuery                     = 'pl+XQuery';                      //  2007-01-01 - https://en.wikipedia.org/wiki/XQuery _ http://www.w3.org/XML/Query/
const PV_XSB                        = 'pl+XSB';                         //  2022-05-12 - https://en.wikipedia.org/wiki/XSB _ https://xsb.sourceforge.net/
const PV_XSLT                       = 'pl+XSLT';                        //  1998-01-01 - https://en.wikipedia.org/wiki/XSLT _ https://www.w3.org/TR/xslt-30/
const PV_Xojo                       = 'pl+Xojo';                        //  2023-10-25 - https://en.wikipedia.org/wiki/Xojo _ http://xojo.com
const PV_Xtend                      = 'pl+Xtend';                       //  2011-01-01 - https://en.wikipedia.org/wiki/Xtend _ https://eclipse.dev/Xtext/xtend/
const PV_YAP_Prolog                 = 'pl+YAP-Prolog';                  //  2013-01-21 - https://en.wikipedia.org/wiki/YAP_(Prolog) _ https://www.dcc.fc.up.pt/~vsc/yap/
const PV_Zig                        = 'pl+Zig';                         //  2016-02-08 - https://en.wikipedia.org/wiki/Zig_(programming_language) _ https://ziglang.org
const PV_eC                         = 'pl+eC';                          //  2004-01-01 - https://en.wikipedia.org/wiki/EC_(programming_language) _ http://ec-lang.org/
const PV_jq                         = 'pl+jq';                          //  2012-08-21 - https://en.wikipedia.org/wiki/Jq_(programming_language) _ https://jqlang.github.io/jq
const PV_k                          = 'pl+k';                           //  0000-00-00 - https://en.wikipedia.org/wiki/K_(programming_language)
const PV_mruby                      = 'pl+mruby';                       //  2012-04-20 - https://en.wikipedia.org/wiki/Mruby _ https://mruby.org
const PV_q                          = 'pl+q';                           //  2003-01-01 - https://en.wikipedia.org/wiki/Q_(programming_language_from_Kx_Systems) _ http://code.kx.com
const PV_rc                         = 'pl+rc';                          //  1989-01-01 - https://en.wikipedia.org/wiki/Rc_(Unix_shell) _ http://doc.cat-v.org/plan_9/4th_edition/papers/rc