/**  Do not modify manually! Generated by graphgen on 2024-12-02T00:11:04.797Z. */

import { Edges, RelFrom, RelTo, type SerializedGraph, Vertices } from "@plangs/graphgen/library";

/** Import user defined classes and types. */
import { VApp, VBundle, VCommunity, VLearning, VLibrary, VLicense, VParadigm, VPlang, VPlatform, VPost, VTag, VTool, VTypeSystem } from ".";
import { PlangsVertex } from "./vertex_base";
import type {
  VAppData,
  VBundleData,
  VCommunityData,
  VLearningData,
  VLibraryData,
  VLicenseData,
  VParadigmData,
  VPlangData,
  VPlatformData,
  VPostData,
  VTagData,
  VToolData,
  VTypeSystemData,
} from "./vertex_data_schemas";

export type TPlangsVertexName =
  | "app"
  | "bundle"
  | "community"
  | "learning"
  | "library"
  | "license"
  | "paradigm"
  | "plang"
  | "platform"
  | "post"
  | "tag"
  | "tool"
  | "typeSystem";

/** Supported relations of each class. */
export type TPlangsRelations = {
  app: "relCommunities" | "relLearning" | "relLicenses" | "relPlatforms" | "relTags" | "relWrittenWith";
  bundle: "relPlangs" | "relTools";
  community: "relApps" | "relLearning" | "relLibraries" | "relPlangs" | "relTags" | "relTools";
  learning: "relApps" | "relCommunities" | "relLibraries" | "relPlangs" | "relTags" | "relTools";
  library: "relCommunities" | "relLearning" | "relLicenses" | "relPlangs" | "relPlatforms" | "relTags" | "relWrittenWith";
  license: "relApps" | "relLibraries" | "relPlangs" | "relTools";
  paradigm: "relPlangs";
  plang:
    | "relApps"
    | "relBundles"
    | "relCommunities"
    | "relCompilesTo"
    | "relDialectOf"
    | "relDialects"
    | "relImplementedBy"
    | "relImplements"
    | "relInfluenced"
    | "relInfluencedBy"
    | "relLearning"
    | "relLibraries"
    | "relLicenses"
    | "relParadigms"
    | "relPlatforms"
    | "relPosts"
    | "relTags"
    | "relTargetOf"
    | "relTools"
    | "relToolsUsing"
    | "relTypeSystems"
    | "relUsedInLibrary"
    | "relUsedToWrite"
    | "relWrittenWith";
  platform: "relApps" | "relLibraries" | "relPlangs" | "relTools";
  post: "relPlangs";
  tag: "relApps" | "relCommunities" | "relLearning" | "relLibraries" | "relPlangs" | "relTools";
  tool: "relBundles" | "relCommunities" | "relLearning" | "relLicenses" | "relPlangs" | "relPlatforms" | "relTags" | "relWrittenWith";
  typeSystem: "relPlangs";
};

/** Every Generated Vertex Class. */
export type TPlangsVertexClass =
  | VApp
  | VBundle
  | VCommunity
  | VLearning
  | VLibrary
  | VLicense
  | VParadigm
  | VPlang
  | VPlatform
  | VPost
  | VTag
  | VTool
  | VTypeSystem;

/** Used for better autocomplete. */
export type TPlangsVClassByName = {
  app: VApp;
  bundle: VBundle;
  community: VCommunity;
  learning: VLearning;
  library: VLibrary;
  license: VLicense;
  paradigm: VParadigm;
  plang: VPlang;
  platform: VPlatform;
  post: VPost;
  tag: VTag;
  tool: VTool;
  typeSystem: VTypeSystem;
};

/** Supported edges of the graph. */
export type TPlangsEdgeName = keyof PlangsGraphBase["edges"];

/** Base class for the Plangs graph, generated from its specification. */
export class PlangsGraphBase {
  /** Return a type checked object identifying a relationship of a specific kind of Vertex. */
  static relConfig<T extends TPlangsVertexName>(vertexName: T, vertexRel: TPlangsRelations[T]) {
    const klass = PlangsGraphBase.vertexClass(vertexName);
    // @ts-ignore correct by construction.
    const rel = klass.relations[vertexRel];
    return { kind: "rel", edgeName: rel.edgeName as TPlangsEdgeName, direction: rel.direction as "direct" | "inverse" } as const;
  }

  /** Return a type checked object identifying a property of the class that is "readable" (a prop returning a String, Boolean or Nunber). */
  static propConfig<T extends TPlangsVertexName>(vertexName: T, vertexProp: keyof TPlangsVClassByName[T]) {
    return { kind: "prop", vertexName: vertexName as TPlangsVertexName, vertexProp: vertexProp as string } as const;
  }

  /** Get a Vertex class by its Vertex name. */
  static vertexClass<T extends TPlangsVertexName>(vertexName: T) {
    // We cannot use a Map here because each of the classes will not be initialized yet.
    if (vertexName === "app") return VApp;
    if (vertexName === "bundle") return VBundle;
    if (vertexName === "community") return VCommunity;
    if (vertexName === "learning") return VLearning;
    if (vertexName === "library") return VLibrary;
    if (vertexName === "license") return VLicense;
    if (vertexName === "paradigm") return VParadigm;
    if (vertexName === "plang") return VPlang;
    if (vertexName === "platform") return VPlatform;
    if (vertexName === "post") return VPost;
    if (vertexName === "tag") return VTag;
    if (vertexName === "tool") return VTool;
    if (vertexName === "typeSystem") return VTypeSystem;
  }

  // Create a Vertices instances for each vertex.

  readonly app = new Vertices<VApp>("app", "app", key => new VApp(this, key));
  readonly bundle = new Vertices<VBundle>("bundle", "bun", key => new VBundle(this, key));
  readonly community = new Vertices<VCommunity>("community", "comm", key => new VCommunity(this, key));
  readonly learning = new Vertices<VLearning>("learning", "learn", key => new VLearning(this, key));
  readonly library = new Vertices<VLibrary>("library", "lib", key => new VLibrary(this, key));
  readonly license = new Vertices<VLicense>("license", "lic", key => new VLicense(this, key));
  readonly paradigm = new Vertices<VParadigm>("paradigm", "para", key => new VParadigm(this, key));
  readonly plang = new Vertices<VPlang>("plang", "pl", key => new VPlang(this, key));
  readonly platform = new Vertices<VPlatform>("platform", "plat", key => new VPlatform(this, key));
  readonly post = new Vertices<VPost>("post", "post", key => new VPost(this, key));
  readonly tag = new Vertices<VTag>("tag", "tag", key => new VTag(this, key));
  readonly tool = new Vertices<VTool>("tool", "tool", key => new VTool(this, key));
  readonly typeSystem = new Vertices<VTypeSystem>("typeSystem", "tsys", key => new VTypeSystem(this, key));

  /** All vertex collections. */
  readonly vertices = {
    app: this.app,
    bundle: this.bundle,
    community: this.community,
    learning: this.learning,
    library: this.library,
    license: this.license,
    paradigm: this.paradigm,
    plang: this.plang,
    platform: this.platform,
    post: this.post,
    tag: this.tag,
    tool: this.tool,
    typeSystem: this.typeSystem,
  } as const;

  /** All edge collections. */
  readonly edges = {
    appRelPlatforms: new Edges(this.app, this.platform, "Platforms supported", "Apps supporting this"),
    appRelWrittenWith: new Edges(this.app, this.plang, "Plangs used to implement this", "Apps implemented with this"),
    bundleRelPlangs: new Edges(this.bundle, this.plang, "Plangs this Bundle is for", "Bundles of Tools for this"),
    bundleRelTools: new Edges(this.bundle, this.tool, "Tools in this", "Bundles including this"),
    communityRelApps: new Edges(this.community, this.app, "Apps supported", "Communities suporting this"),
    communityRelLibraries: new Edges(this.community, this.library, "Libraries supported", "Communities suporting this"),
    communityRelPlangs: new Edges(this.community, this.plang, "Plangs supported", "Communities suporting this"),
    communityRelTools: new Edges(this.community, this.tool, "Tools supported", "Communities suporting this"),
    learningRelApps: new Edges(this.learning, this.app, "Apps supported", "Learning resources"),
    learningRelCommunities: new Edges(this.learning, this.community, "Communities supporting this", "Learning resources"),
    learningRelLibraries: new Edges(this.learning, this.library, "Libraries supported", "Learning resources"),
    learningRelPlangs: new Edges(this.learning, this.plang, "Plangs covered", "Learning resources"),
    learningRelTools: new Edges(this.learning, this.tool, "Tools supported", "Learning resources"),
    libraryRelPlangs: new Edges(this.library, this.plang, "Plangs supported", "Software Libraries"),
    libraryRelPlatforms: new Edges(this.library, this.platform, "Platforms supported", "Libraries supporting this"),
    libraryRelWrittenWith: new Edges(this.library, this.plang, "Plangs used", "Libraries made with this"),
    licenseRelApps: new Edges(this.license, this.app, "Apps using this", "Licenses"),
    licenseRelLibraries: new Edges(this.license, this.library, "Libraries using this", "Licenses"),
    licenseRelPlangs: new Edges(this.license, this.plang, "Plangs using this", "Licenses"),
    licenseRelTools: new Edges(this.license, this.tool, "Tools using this", "Licenses"),
    plangRelCompilesTo: new Edges(this.plang, this.plang, "Transpiling targets", "Plangs compiling to this"),
    plangRelDialectOf: new Edges(this.plang, this.plang, "Plangs this is a Dialect of", "Dialects"),
    plangRelImplements: new Edges(this.plang, this.plang, "Plangs this Implements", "Plangs implementing this"),
    plangRelInfluencedBy: new Edges(this.plang, this.plang, "Plangs that influenced this", "Plangs this influenced"),
    plangRelParadigms: new Edges(this.plang, this.paradigm, "Paradigms implemented", "Plangs implementing this"),
    plangRelPlatforms: new Edges(this.plang, this.platform, "Platforms supported", "Plangs supporting this"),
    plangRelTools: new Edges(this.plang, this.tool, "Tools for this", "Plangs supported"),
    plangRelTypeSystems: new Edges(this.plang, this.typeSystem, "Type Systems implemented", "Plangs implementing this"),
    plangRelWrittenWith: new Edges(this.plang, this.plang, "Plangs used to implement this", "Plangs implemented with this"),
    postRelPlangs: new Edges(this.post, this.plang, "Plangs covered", "Posts talking about this"),
    tagRelApps: new Edges(this.tag, this.app, "Apps tagged", "Tags"),
    tagRelCommunities: new Edges(this.tag, this.community, "Communities tagged", "Tags"),
    tagRelLearning: new Edges(this.tag, this.learning, "Learning resources tagged", "Tags"),
    tagRelLibraries: new Edges(this.tag, this.library, "Libraries tagged", "Tags"),
    tagRelPlangs: new Edges(this.tag, this.plang, "Plangs tagged", "Tags"),
    tagRelTools: new Edges(this.tag, this.tool, "Tools tagged", "Tags"),
    toolRelPlatforms: new Edges(this.tool, this.platform, "Platforms supported", "Tools supporting this"),
    toolRelWrittenWith: new Edges(this.tool, this.plang, "Plangs used to implement this", "Tools implemented with this"),
  } as const;

  toJSON(): SerializedGraph {
    return {
      vertices: Object.fromEntries(Object.entries(this.vertices).map(([k, v]) => [k, v.toJSON()])),
      edges: Object.fromEntries(Object.entries(this.edges).map(([k, e]) => [k, e.toJSON()])),
    };
  }

  loadJSON(data: SerializedGraph): this {
    for (const [vertexName, vertices] of Object.entries(data.vertices)) {
      const map = this.vertices[vertexName as TPlangsVertexName];
      for (const [vertexKey, vertexData] of Object.entries(vertices)) {
        map.set(vertexKey as any, vertexData as any);
      }
    }
    for (const [edgeName, edges] of Object.entries(data.edges)) {
      const map = this.edges[edgeName as keyof typeof this.edges];
      for (const [fromKey, toKeys] of Object.entries(edges)) {
        map.add(fromKey as any, ...(toKeys as any[]));
      }
    }
    return this;
  }
}

/** Type of the key of an instance of {@link VApp}. */
export type VAppKey = `app+${string}`;

/** Software Application */
export abstract class VAppBase extends PlangsVertex<"app", VAppData> {
  static readonly keyPrefix = "app";
  static readonly vertexName = "app";
  static readonly vertexDesc = "Software Application";

  /** Describes the edges and direction used for every relationship in this Vertex. */
  static readonly relations = {
    relCommunities: { edgeName: "communityRelApps", direction: "inverse" },
    relLearning: { edgeName: "learningRelApps", direction: "inverse" },
    relLicenses: { edgeName: "licenseRelApps", direction: "inverse" },
    relPlatforms: { edgeName: "appRelPlatforms", direction: "direct" },
    relTags: { edgeName: "tagRelApps", direction: "inverse" },
    relWrittenWith: { edgeName: "appRelWrittenWith", direction: "direct" },
  } as const;

  readonly vertexDesc = VAppBase.vertexDesc;

  /** Communities suporting this `VCommunity-[relApps]->(this:VApp)`. Inverse: {@link VCommunity.relApps}. */
  get relCommunities() {
    return new RelTo(this as unknown as VApp, this.graph.edges.communityRelApps);
  }

  /** Learning resources `VLearning-[relApps]->(this:VApp)`. Inverse: {@link VLearning.relApps}. */
  get relLearning() {
    return new RelTo(this as unknown as VApp, this.graph.edges.learningRelApps);
  }

  /** Licenses `VLicense-[relApps]->(this:VApp)`. Inverse: {@link VLicense.relApps}. */
  get relLicenses() {
    return new RelTo(this as unknown as VApp, this.graph.edges.licenseRelApps);
  }

  /** Platforms supported `(this:VApp)-[relPlatforms]->VPlatform`. Inverse: {@link VPlatform.relApps}. */
  get relPlatforms() {
    return new RelFrom(this as unknown as VApp, this.graph.edges.appRelPlatforms);
  }

  /** Tags `VTag-[relApps]->(this:VApp)`. Inverse: {@link VTag.relApps}. */
  get relTags() {
    return new RelTo(this as unknown as VApp, this.graph.edges.tagRelApps);
  }

  /** Plangs used to implement this `(this:VApp)-[relWrittenWith]->VPlang`. Inverse: {@link VPlang.relApps}. */
  get relWrittenWith() {
    return new RelFrom(this as unknown as VApp, this.graph.edges.appRelWrittenWith);
  }
}

/** Type of the key of an instance of {@link VBundle}. */
export type VBundleKey = `bun+${string}`;

/** Bundle of Tools */
export abstract class VBundleBase extends PlangsVertex<"bun", VBundleData> {
  static readonly keyPrefix = "bun";
  static readonly vertexName = "bundle";
  static readonly vertexDesc = "Bundle of Tools";

  /** Describes the edges and direction used for every relationship in this Vertex. */
  static readonly relations = {
    relPlangs: { edgeName: "bundleRelPlangs", direction: "direct" },
    relTools: { edgeName: "bundleRelTools", direction: "direct" },
  } as const;

  readonly vertexDesc = VBundleBase.vertexDesc;

  /** Plangs this Bundle is for `(this:VBundle)-[relPlangs]->VPlang`. Inverse: {@link VPlang.relBundles}. */
  get relPlangs() {
    return new RelFrom(this as unknown as VBundle, this.graph.edges.bundleRelPlangs);
  }

  /** Tools in this `(this:VBundle)-[relTools]->VTool`. Inverse: {@link VTool.relBundles}. */
  get relTools() {
    return new RelFrom(this as unknown as VBundle, this.graph.edges.bundleRelTools);
  }
}

/** Type of the key of an instance of {@link VCommunity}. */
export type VCommunityKey = `comm+${string}`;

/** Community */
export abstract class VCommunityBase extends PlangsVertex<"comm", VCommunityData> {
  static readonly keyPrefix = "comm";
  static readonly vertexName = "community";
  static readonly vertexDesc = "Community";

  /** Describes the edges and direction used for every relationship in this Vertex. */
  static readonly relations = {
    relApps: { edgeName: "communityRelApps", direction: "direct" },
    relLearning: { edgeName: "learningRelCommunities", direction: "inverse" },
    relLibraries: { edgeName: "communityRelLibraries", direction: "direct" },
    relPlangs: { edgeName: "communityRelPlangs", direction: "direct" },
    relTags: { edgeName: "tagRelCommunities", direction: "inverse" },
    relTools: { edgeName: "communityRelTools", direction: "direct" },
  } as const;

  readonly vertexDesc = VCommunityBase.vertexDesc;

  /** Apps supported `(this:VCommunity)-[relApps]->VApp`. Inverse: {@link VApp.relCommunities}. */
  get relApps() {
    return new RelFrom(this as unknown as VCommunity, this.graph.edges.communityRelApps);
  }

  /** Learning resources `VLearning-[relCommunities]->(this:VCommunity)`. Inverse: {@link VLearning.relCommunities}. */
  get relLearning() {
    return new RelTo(this as unknown as VCommunity, this.graph.edges.learningRelCommunities);
  }

  /** Libraries supported `(this:VCommunity)-[relLibraries]->VLibrary`. Inverse: {@link VLibrary.relCommunities}. */
  get relLibraries() {
    return new RelFrom(this as unknown as VCommunity, this.graph.edges.communityRelLibraries);
  }

  /** Plangs supported `(this:VCommunity)-[relPlangs]->VPlang`. Inverse: {@link VPlang.relCommunities}. */
  get relPlangs() {
    return new RelFrom(this as unknown as VCommunity, this.graph.edges.communityRelPlangs);
  }

  /** Tags `VTag-[relCommunities]->(this:VCommunity)`. Inverse: {@link VTag.relCommunities}. */
  get relTags() {
    return new RelTo(this as unknown as VCommunity, this.graph.edges.tagRelCommunities);
  }

  /** Tools supported `(this:VCommunity)-[relTools]->VTool`. Inverse: {@link VTool.relCommunities}. */
  get relTools() {
    return new RelFrom(this as unknown as VCommunity, this.graph.edges.communityRelTools);
  }
}

/** Type of the key of an instance of {@link VLearning}. */
export type VLearningKey = `learn+${string}`;

/** Learning Resource */
export abstract class VLearningBase extends PlangsVertex<"learn", VLearningData> {
  static readonly keyPrefix = "learn";
  static readonly vertexName = "learning";
  static readonly vertexDesc = "Learning Resource";

  /** Describes the edges and direction used for every relationship in this Vertex. */
  static readonly relations = {
    relApps: { edgeName: "learningRelApps", direction: "direct" },
    relCommunities: { edgeName: "learningRelCommunities", direction: "direct" },
    relLibraries: { edgeName: "learningRelLibraries", direction: "direct" },
    relPlangs: { edgeName: "learningRelPlangs", direction: "direct" },
    relTags: { edgeName: "tagRelLearning", direction: "inverse" },
    relTools: { edgeName: "learningRelTools", direction: "direct" },
  } as const;

  readonly vertexDesc = VLearningBase.vertexDesc;

  /** Apps supported `(this:VLearning)-[relApps]->VApp`. Inverse: {@link VApp.relLearning}. */
  get relApps() {
    return new RelFrom(this as unknown as VLearning, this.graph.edges.learningRelApps);
  }

  /** Communities supporting this `(this:VLearning)-[relCommunities]->VCommunity`. Inverse: {@link VCommunity.relLearning}. */
  get relCommunities() {
    return new RelFrom(this as unknown as VLearning, this.graph.edges.learningRelCommunities);
  }

  /** Libraries supported `(this:VLearning)-[relLibraries]->VLibrary`. Inverse: {@link VLibrary.relLearning}. */
  get relLibraries() {
    return new RelFrom(this as unknown as VLearning, this.graph.edges.learningRelLibraries);
  }

  /** Plangs covered `(this:VLearning)-[relPlangs]->VPlang`. Inverse: {@link VPlang.relLearning}. */
  get relPlangs() {
    return new RelFrom(this as unknown as VLearning, this.graph.edges.learningRelPlangs);
  }

  /** Tags `VTag-[relLearning]->(this:VLearning)`. Inverse: {@link VTag.relLearning}. */
  get relTags() {
    return new RelTo(this as unknown as VLearning, this.graph.edges.tagRelLearning);
  }

  /** Tools supported `(this:VLearning)-[relTools]->VTool`. Inverse: {@link VTool.relLearning}. */
  get relTools() {
    return new RelFrom(this as unknown as VLearning, this.graph.edges.learningRelTools);
  }
}

/** Type of the key of an instance of {@link VLibrary}. */
export type VLibraryKey = `lib+${string}`;

/** Software Library */
export abstract class VLibraryBase extends PlangsVertex<"lib", VLibraryData> {
  static readonly keyPrefix = "lib";
  static readonly vertexName = "library";
  static readonly vertexDesc = "Software Library";

  /** Describes the edges and direction used for every relationship in this Vertex. */
  static readonly relations = {
    relCommunities: { edgeName: "communityRelLibraries", direction: "inverse" },
    relLearning: { edgeName: "learningRelLibraries", direction: "inverse" },
    relLicenses: { edgeName: "licenseRelLibraries", direction: "inverse" },
    relPlangs: { edgeName: "libraryRelPlangs", direction: "direct" },
    relPlatforms: { edgeName: "libraryRelPlatforms", direction: "direct" },
    relTags: { edgeName: "tagRelLibraries", direction: "inverse" },
    relWrittenWith: { edgeName: "libraryRelWrittenWith", direction: "direct" },
  } as const;

  readonly vertexDesc = VLibraryBase.vertexDesc;

  /** Communities suporting this `VCommunity-[relLibraries]->(this:VLibrary)`. Inverse: {@link VCommunity.relLibraries}. */
  get relCommunities() {
    return new RelTo(this as unknown as VLibrary, this.graph.edges.communityRelLibraries);
  }

  /** Learning resources `VLearning-[relLibraries]->(this:VLibrary)`. Inverse: {@link VLearning.relLibraries}. */
  get relLearning() {
    return new RelTo(this as unknown as VLibrary, this.graph.edges.learningRelLibraries);
  }

  /** Licenses `VLicense-[relLibraries]->(this:VLibrary)`. Inverse: {@link VLicense.relLibraries}. */
  get relLicenses() {
    return new RelTo(this as unknown as VLibrary, this.graph.edges.licenseRelLibraries);
  }

  /** Plangs supported `(this:VLibrary)-[relPlangs]->VPlang`. Inverse: {@link VPlang.relLibraries}. */
  get relPlangs() {
    return new RelFrom(this as unknown as VLibrary, this.graph.edges.libraryRelPlangs);
  }

  /** Platforms supported `(this:VLibrary)-[relPlatforms]->VPlatform`. Inverse: {@link VPlatform.relLibraries}. */
  get relPlatforms() {
    return new RelFrom(this as unknown as VLibrary, this.graph.edges.libraryRelPlatforms);
  }

  /** Tags `VTag-[relLibraries]->(this:VLibrary)`. Inverse: {@link VTag.relLibraries}. */
  get relTags() {
    return new RelTo(this as unknown as VLibrary, this.graph.edges.tagRelLibraries);
  }

  /** Plangs used `(this:VLibrary)-[relWrittenWith]->VPlang`. Inverse: {@link VPlang.relUsedInLibrary}. */
  get relWrittenWith() {
    return new RelFrom(this as unknown as VLibrary, this.graph.edges.libraryRelWrittenWith);
  }
}

/** Type of the key of an instance of {@link VLicense}. */
export type VLicenseKey = `lic+${string}`;

/** Software License */
export abstract class VLicenseBase extends PlangsVertex<"lic", VLicenseData> {
  static readonly keyPrefix = "lic";
  static readonly vertexName = "license";
  static readonly vertexDesc = "Software License";

  /** Describes the edges and direction used for every relationship in this Vertex. */
  static readonly relations = {
    relApps: { edgeName: "licenseRelApps", direction: "direct" },
    relLibraries: { edgeName: "licenseRelLibraries", direction: "direct" },
    relPlangs: { edgeName: "licenseRelPlangs", direction: "direct" },
    relTools: { edgeName: "licenseRelTools", direction: "direct" },
  } as const;

  readonly vertexDesc = VLicenseBase.vertexDesc;

  /** Apps using this `(this:VLicense)-[relApps]->VApp`. Inverse: {@link VApp.relLicenses}. */
  get relApps() {
    return new RelFrom(this as unknown as VLicense, this.graph.edges.licenseRelApps);
  }

  /** Libraries using this `(this:VLicense)-[relLibraries]->VLibrary`. Inverse: {@link VLibrary.relLicenses}. */
  get relLibraries() {
    return new RelFrom(this as unknown as VLicense, this.graph.edges.licenseRelLibraries);
  }

  /** Plangs using this `(this:VLicense)-[relPlangs]->VPlang`. Inverse: {@link VPlang.relLicenses}. */
  get relPlangs() {
    return new RelFrom(this as unknown as VLicense, this.graph.edges.licenseRelPlangs);
  }

  /** Tools using this `(this:VLicense)-[relTools]->VTool`. Inverse: {@link VTool.relLicenses}. */
  get relTools() {
    return new RelFrom(this as unknown as VLicense, this.graph.edges.licenseRelTools);
  }
}

/** Type of the key of an instance of {@link VParadigm}. */
export type VParadigmKey = `para+${string}`;

/** Programming Language Paradigm */
export abstract class VParadigmBase extends PlangsVertex<"para", VParadigmData> {
  static readonly keyPrefix = "para";
  static readonly vertexName = "paradigm";
  static readonly vertexDesc = "Programming Language Paradigm";

  /** Describes the edges and direction used for every relationship in this Vertex. */
  static readonly relations = { relPlangs: { edgeName: "plangRelParadigms", direction: "inverse" } } as const;

  readonly vertexDesc = VParadigmBase.vertexDesc;

  /** Plangs implementing this `VPlang-[relParadigms]->(this:VParadigm)`. Inverse: {@link VPlang.relParadigms}. */
  get relPlangs() {
    return new RelTo(this as unknown as VParadigm, this.graph.edges.plangRelParadigms);
  }
}

/** Type of the key of an instance of {@link VPlang}. */
export type VPlangKey = `pl+${string}`;

/** Programming Language */
export abstract class VPlangBase extends PlangsVertex<"pl", VPlangData> {
  static readonly keyPrefix = "pl";
  static readonly vertexName = "plang";
  static readonly vertexDesc = "Programming Language";

  /** Describes the edges and direction used for every relationship in this Vertex. */
  static readonly relations = {
    relApps: { edgeName: "appRelWrittenWith", direction: "inverse" },
    relBundles: { edgeName: "bundleRelPlangs", direction: "inverse" },
    relCommunities: { edgeName: "communityRelPlangs", direction: "inverse" },
    relCompilesTo: { edgeName: "plangRelCompilesTo", direction: "direct" },
    relDialectOf: { edgeName: "plangRelDialectOf", direction: "direct" },
    relDialects: { edgeName: "plangRelDialectOf", direction: "inverse" },
    relImplementedBy: { edgeName: "plangRelImplements", direction: "inverse" },
    relImplements: { edgeName: "plangRelImplements", direction: "direct" },
    relInfluenced: { edgeName: "plangRelInfluencedBy", direction: "inverse" },
    relInfluencedBy: { edgeName: "plangRelInfluencedBy", direction: "direct" },
    relLearning: { edgeName: "learningRelPlangs", direction: "inverse" },
    relLibraries: { edgeName: "libraryRelPlangs", direction: "inverse" },
    relLicenses: { edgeName: "licenseRelPlangs", direction: "inverse" },
    relParadigms: { edgeName: "plangRelParadigms", direction: "direct" },
    relPlatforms: { edgeName: "plangRelPlatforms", direction: "direct" },
    relPosts: { edgeName: "postRelPlangs", direction: "inverse" },
    relTags: { edgeName: "tagRelPlangs", direction: "inverse" },
    relTargetOf: { edgeName: "plangRelCompilesTo", direction: "inverse" },
    relTools: { edgeName: "plangRelTools", direction: "direct" },
    relToolsUsing: { edgeName: "toolRelWrittenWith", direction: "inverse" },
    relTypeSystems: { edgeName: "plangRelTypeSystems", direction: "direct" },
    relUsedInLibrary: { edgeName: "libraryRelWrittenWith", direction: "inverse" },
    relUsedToWrite: { edgeName: "plangRelWrittenWith", direction: "inverse" },
    relWrittenWith: { edgeName: "plangRelWrittenWith", direction: "direct" },
  } as const;

  readonly vertexDesc = VPlangBase.vertexDesc;

  /** Apps implemented with this `VApp-[relWrittenWith]->(this:VPlang)`. Inverse: {@link VApp.relWrittenWith}. */
  get relApps() {
    return new RelTo(this as unknown as VPlang, this.graph.edges.appRelWrittenWith);
  }

  /** Bundles of Tools for this `VBundle-[relPlangs]->(this:VPlang)`. Inverse: {@link VBundle.relPlangs}. */
  get relBundles() {
    return new RelTo(this as unknown as VPlang, this.graph.edges.bundleRelPlangs);
  }

  /** Communities suporting this `VCommunity-[relPlangs]->(this:VPlang)`. Inverse: {@link VCommunity.relPlangs}. */
  get relCommunities() {
    return new RelTo(this as unknown as VPlang, this.graph.edges.communityRelPlangs);
  }

  /** Transpiling targets `(this:VPlang)-[relCompilesTo]->VPlang`. Inverse: {@link VPlang.relTargetOf}. */
  get relCompilesTo() {
    return new RelFrom(this as unknown as VPlang, this.graph.edges.plangRelCompilesTo);
  }

  /** Plangs this is a Dialect of `(this:VPlang)-[relDialectOf]->VPlang`. Inverse: {@link VPlang.relDialects}. */
  get relDialectOf() {
    return new RelFrom(this as unknown as VPlang, this.graph.edges.plangRelDialectOf);
  }

  /** Dialects `VPlang-[relDialectOf]->(this:VPlang)`. Inverse: {@link VPlang.relDialectOf}. */
  get relDialects() {
    return new RelTo(this as unknown as VPlang, this.graph.edges.plangRelDialectOf);
  }

  /** Plangs implementing this `VPlang-[relImplements]->(this:VPlang)`. Inverse: {@link VPlang.relImplements}. */
  get relImplementedBy() {
    return new RelTo(this as unknown as VPlang, this.graph.edges.plangRelImplements);
  }

  /** Plangs this Implements `(this:VPlang)-[relImplements]->VPlang`. Inverse: {@link VPlang.relImplementedBy}. */
  get relImplements() {
    return new RelFrom(this as unknown as VPlang, this.graph.edges.plangRelImplements);
  }

  /** Plangs this influenced `VPlang-[relInfluencedBy]->(this:VPlang)`. Inverse: {@link VPlang.relInfluencedBy}. */
  get relInfluenced() {
    return new RelTo(this as unknown as VPlang, this.graph.edges.plangRelInfluencedBy);
  }

  /** Plangs that influenced this `(this:VPlang)-[relInfluencedBy]->VPlang`. Inverse: {@link VPlang.relInfluenced}. */
  get relInfluencedBy() {
    return new RelFrom(this as unknown as VPlang, this.graph.edges.plangRelInfluencedBy);
  }

  /** Learning resources `VLearning-[relPlangs]->(this:VPlang)`. Inverse: {@link VLearning.relPlangs}. */
  get relLearning() {
    return new RelTo(this as unknown as VPlang, this.graph.edges.learningRelPlangs);
  }

  /** Software Libraries `VLibrary-[relPlangs]->(this:VPlang)`. Inverse: {@link VLibrary.relPlangs}. */
  get relLibraries() {
    return new RelTo(this as unknown as VPlang, this.graph.edges.libraryRelPlangs);
  }

  /** Licenses `VLicense-[relPlangs]->(this:VPlang)`. Inverse: {@link VLicense.relPlangs}. */
  get relLicenses() {
    return new RelTo(this as unknown as VPlang, this.graph.edges.licenseRelPlangs);
  }

  /** Paradigms implemented `(this:VPlang)-[relParadigms]->VParadigm`. Inverse: {@link VParadigm.relPlangs}. */
  get relParadigms() {
    return new RelFrom(this as unknown as VPlang, this.graph.edges.plangRelParadigms);
  }

  /** Platforms supported `(this:VPlang)-[relPlatforms]->VPlatform`. Inverse: {@link VPlatform.relPlangs}. */
  get relPlatforms() {
    return new RelFrom(this as unknown as VPlang, this.graph.edges.plangRelPlatforms);
  }

  /** Posts talking about this `VPost-[relPlangs]->(this:VPlang)`. Inverse: {@link VPost.relPlangs}. */
  get relPosts() {
    return new RelTo(this as unknown as VPlang, this.graph.edges.postRelPlangs);
  }

  /** Tags `VTag-[relPlangs]->(this:VPlang)`. Inverse: {@link VTag.relPlangs}. */
  get relTags() {
    return new RelTo(this as unknown as VPlang, this.graph.edges.tagRelPlangs);
  }

  /** Plangs compiling to this `VPlang-[relCompilesTo]->(this:VPlang)`. Inverse: {@link VPlang.relCompilesTo}. */
  get relTargetOf() {
    return new RelTo(this as unknown as VPlang, this.graph.edges.plangRelCompilesTo);
  }

  /** Tools for this `(this:VPlang)-[relTools]->VTool`. Inverse: {@link VTool.relPlangs}. */
  get relTools() {
    return new RelFrom(this as unknown as VPlang, this.graph.edges.plangRelTools);
  }

  /** Tools implemented with this `VTool-[relWrittenWith]->(this:VPlang)`. Inverse: {@link VTool.relWrittenWith}. */
  get relToolsUsing() {
    return new RelTo(this as unknown as VPlang, this.graph.edges.toolRelWrittenWith);
  }

  /** Type Systems implemented `(this:VPlang)-[relTypeSystems]->VTypeSystem`. Inverse: {@link VTypeSystem.relPlangs}. */
  get relTypeSystems() {
    return new RelFrom(this as unknown as VPlang, this.graph.edges.plangRelTypeSystems);
  }

  /** Libraries made with this `VLibrary-[relWrittenWith]->(this:VPlang)`. Inverse: {@link VLibrary.relWrittenWith}. */
  get relUsedInLibrary() {
    return new RelTo(this as unknown as VPlang, this.graph.edges.libraryRelWrittenWith);
  }

  /** Plangs implemented with this `VPlang-[relWrittenWith]->(this:VPlang)`. Inverse: {@link VPlang.relWrittenWith}. */
  get relUsedToWrite() {
    return new RelTo(this as unknown as VPlang, this.graph.edges.plangRelWrittenWith);
  }

  /** Plangs used to implement this `(this:VPlang)-[relWrittenWith]->VPlang`. Inverse: {@link VPlang.relUsedToWrite}. */
  get relWrittenWith() {
    return new RelFrom(this as unknown as VPlang, this.graph.edges.plangRelWrittenWith);
  }
}

/** Type of the key of an instance of {@link VPlatform}. */
export type VPlatformKey = `plat+${string}`;

/** Platform where Software runs */
export abstract class VPlatformBase extends PlangsVertex<"plat", VPlatformData> {
  static readonly keyPrefix = "plat";
  static readonly vertexName = "platform";
  static readonly vertexDesc = "Platform where Software runs";

  /** Describes the edges and direction used for every relationship in this Vertex. */
  static readonly relations = {
    relApps: { edgeName: "appRelPlatforms", direction: "inverse" },
    relLibraries: { edgeName: "libraryRelPlatforms", direction: "inverse" },
    relPlangs: { edgeName: "plangRelPlatforms", direction: "inverse" },
    relTools: { edgeName: "toolRelPlatforms", direction: "inverse" },
  } as const;

  readonly vertexDesc = VPlatformBase.vertexDesc;

  /** Apps supporting this `VApp-[relPlatforms]->(this:VPlatform)`. Inverse: {@link VApp.relPlatforms}. */
  get relApps() {
    return new RelTo(this as unknown as VPlatform, this.graph.edges.appRelPlatforms);
  }

  /** Libraries supporting this `VLibrary-[relPlatforms]->(this:VPlatform)`. Inverse: {@link VLibrary.relPlatforms}. */
  get relLibraries() {
    return new RelTo(this as unknown as VPlatform, this.graph.edges.libraryRelPlatforms);
  }

  /** Plangs supporting this `VPlang-[relPlatforms]->(this:VPlatform)`. Inverse: {@link VPlang.relPlatforms}. */
  get relPlangs() {
    return new RelTo(this as unknown as VPlatform, this.graph.edges.plangRelPlatforms);
  }

  /** Tools supporting this `VTool-[relPlatforms]->(this:VPlatform)`. Inverse: {@link VTool.relPlatforms}. */
  get relTools() {
    return new RelTo(this as unknown as VPlatform, this.graph.edges.toolRelPlatforms);
  }
}

/** Type of the key of an instance of {@link VPost}. */
export type VPostKey = `post+${string}`;

/** Blog Post */
export abstract class VPostBase extends PlangsVertex<"post", VPostData> {
  static readonly keyPrefix = "post";
  static readonly vertexName = "post";
  static readonly vertexDesc = "Blog Post";

  /** Describes the edges and direction used for every relationship in this Vertex. */
  static readonly relations = { relPlangs: { edgeName: "postRelPlangs", direction: "direct" } } as const;

  readonly vertexDesc = VPostBase.vertexDesc;

  /** Plangs covered `(this:VPost)-[relPlangs]->VPlang`. Inverse: {@link VPlang.relPosts}. */
  get relPlangs() {
    return new RelFrom(this as unknown as VPost, this.graph.edges.postRelPlangs);
  }
}

/** Type of the key of an instance of {@link VTag}. */
export type VTagKey = `tag+${string}`;

/** Tag */
export abstract class VTagBase extends PlangsVertex<"tag", VTagData> {
  static readonly keyPrefix = "tag";
  static readonly vertexName = "tag";
  static readonly vertexDesc = "Tag";

  /** Describes the edges and direction used for every relationship in this Vertex. */
  static readonly relations = {
    relApps: { edgeName: "tagRelApps", direction: "direct" },
    relCommunities: { edgeName: "tagRelCommunities", direction: "direct" },
    relLearning: { edgeName: "tagRelLearning", direction: "direct" },
    relLibraries: { edgeName: "tagRelLibraries", direction: "direct" },
    relPlangs: { edgeName: "tagRelPlangs", direction: "direct" },
    relTools: { edgeName: "tagRelTools", direction: "direct" },
  } as const;

  readonly vertexDesc = VTagBase.vertexDesc;

  /** Apps tagged `(this:VTag)-[relApps]->VApp`. Inverse: {@link VApp.relTags}. */
  get relApps() {
    return new RelFrom(this as unknown as VTag, this.graph.edges.tagRelApps);
  }

  /** Communities tagged `(this:VTag)-[relCommunities]->VCommunity`. Inverse: {@link VCommunity.relTags}. */
  get relCommunities() {
    return new RelFrom(this as unknown as VTag, this.graph.edges.tagRelCommunities);
  }

  /** Learning resources tagged `(this:VTag)-[relLearning]->VLearning`. Inverse: {@link VLearning.relTags}. */
  get relLearning() {
    return new RelFrom(this as unknown as VTag, this.graph.edges.tagRelLearning);
  }

  /** Libraries tagged `(this:VTag)-[relLibraries]->VLibrary`. Inverse: {@link VLibrary.relTags}. */
  get relLibraries() {
    return new RelFrom(this as unknown as VTag, this.graph.edges.tagRelLibraries);
  }

  /** Plangs tagged `(this:VTag)-[relPlangs]->VPlang`. Inverse: {@link VPlang.relTags}. */
  get relPlangs() {
    return new RelFrom(this as unknown as VTag, this.graph.edges.tagRelPlangs);
  }

  /** Tools tagged `(this:VTag)-[relTools]->VTool`. Inverse: {@link VTool.relTags}. */
  get relTools() {
    return new RelFrom(this as unknown as VTag, this.graph.edges.tagRelTools);
  }
}

/** Type of the key of an instance of {@link VTool}. */
export type VToolKey = `tool+${string}`;

/** Programming Tool */
export abstract class VToolBase extends PlangsVertex<"tool", VToolData> {
  static readonly keyPrefix = "tool";
  static readonly vertexName = "tool";
  static readonly vertexDesc = "Programming Tool";

  /** Describes the edges and direction used for every relationship in this Vertex. */
  static readonly relations = {
    relBundles: { edgeName: "bundleRelTools", direction: "inverse" },
    relCommunities: { edgeName: "communityRelTools", direction: "inverse" },
    relLearning: { edgeName: "learningRelTools", direction: "inverse" },
    relLicenses: { edgeName: "licenseRelTools", direction: "inverse" },
    relPlangs: { edgeName: "plangRelTools", direction: "inverse" },
    relPlatforms: { edgeName: "toolRelPlatforms", direction: "direct" },
    relTags: { edgeName: "tagRelTools", direction: "inverse" },
    relWrittenWith: { edgeName: "toolRelWrittenWith", direction: "direct" },
  } as const;

  readonly vertexDesc = VToolBase.vertexDesc;

  /** Bundles including this `VBundle-[relTools]->(this:VTool)`. Inverse: {@link VBundle.relTools}. */
  get relBundles() {
    return new RelTo(this as unknown as VTool, this.graph.edges.bundleRelTools);
  }

  /** Communities suporting this `VCommunity-[relTools]->(this:VTool)`. Inverse: {@link VCommunity.relTools}. */
  get relCommunities() {
    return new RelTo(this as unknown as VTool, this.graph.edges.communityRelTools);
  }

  /** Learning resources `VLearning-[relTools]->(this:VTool)`. Inverse: {@link VLearning.relTools}. */
  get relLearning() {
    return new RelTo(this as unknown as VTool, this.graph.edges.learningRelTools);
  }

  /** Licenses `VLicense-[relTools]->(this:VTool)`. Inverse: {@link VLicense.relTools}. */
  get relLicenses() {
    return new RelTo(this as unknown as VTool, this.graph.edges.licenseRelTools);
  }

  /** Plangs supported `VPlang-[relTools]->(this:VTool)`. Inverse: {@link VPlang.relTools}. */
  get relPlangs() {
    return new RelTo(this as unknown as VTool, this.graph.edges.plangRelTools);
  }

  /** Platforms supported `(this:VTool)-[relPlatforms]->VPlatform`. Inverse: {@link VPlatform.relTools}. */
  get relPlatforms() {
    return new RelFrom(this as unknown as VTool, this.graph.edges.toolRelPlatforms);
  }

  /** Tags `VTag-[relTools]->(this:VTool)`. Inverse: {@link VTag.relTools}. */
  get relTags() {
    return new RelTo(this as unknown as VTool, this.graph.edges.tagRelTools);
  }

  /** Plangs used to implement this `(this:VTool)-[relWrittenWith]->VPlang`. Inverse: {@link VPlang.relToolsUsing}. */
  get relWrittenWith() {
    return new RelFrom(this as unknown as VTool, this.graph.edges.toolRelWrittenWith);
  }
}

/** Type of the key of an instance of {@link VTypeSystem}. */
export type VTypeSystemKey = `tsys+${string}`;

/** Type System */
export abstract class VTypeSystemBase extends PlangsVertex<"tsys", VTypeSystemData> {
  static readonly keyPrefix = "tsys";
  static readonly vertexName = "typeSystem";
  static readonly vertexDesc = "Type System";

  /** Describes the edges and direction used for every relationship in this Vertex. */
  static readonly relations = { relPlangs: { edgeName: "plangRelTypeSystems", direction: "inverse" } } as const;

  readonly vertexDesc = VTypeSystemBase.vertexDesc;

  /** Plangs implementing this `VPlang-[relTypeSystems]->(this:VTypeSystem)`. Inverse: {@link VPlang.relTypeSystems}. */
  get relPlangs() {
    return new RelTo(this as unknown as VTypeSystem, this.graph.edges.plangRelTypeSystems);
  }
}
